// 25/26 시즌 아카이브 — league_standings_fixed.txt 에서 자동 변환 (원본 표기 그대로)
// 팀 이름은 그 시즌 당시 이름을 그대로 씁니다. 현재 팀과 이어지는 경우만 aliasMap에 적습니다.
const ARCHIVE_2526 = {
 "season": "25/26",
 "champion": "Embangweni United FC",
 "relegated": [
  "Ekwendeni United FC",
  "Chirambo FC",
  "Chisapa FC"
 ],
 "weeks": [
  {
   "key": 1,
   "short": "1주차",
   "label": "1주차",
   "rows": [
    {
     "pos": 1,
     "team": "Raiply FC",
     "p": 1,
     "w": 1,
     "d": 0,
     "l": 0,
     "f": 5,
     "a": 1,
     "gd": 4,
     "pts": 3
    },
    {
     "pos": 2,
     "team": "Simbowe Stars FC",
     "p": 1,
     "w": 1,
     "d": 0,
     "l": 0,
     "f": 3,
     "a": 1,
     "gd": 2,
     "pts": 3
    },
    {
     "pos": 3,
     "team": "Euthin Kuseli Veterans FC",
     "p": 1,
     "w": 1,
     "d": 0,
     "l": 0,
     "f": 2,
     "a": 1,
     "gd": 1,
     "pts": 3
    },
    {
     "pos": 4,
     "team": "Embangweni United FC",
     "p": 1,
     "w": 1,
     "d": 0,
     "l": 0,
     "f": 2,
     "a": 1,
     "gd": 1,
     "pts": 3
    },
    {
     "pos": 5,
     "team": "Ekwendeni Hardnockers FC",
     "p": 1,
     "w": 0,
     "d": 1,
     "l": 0,
     "f": 1,
     "a": 1,
     "gd": 0,
     "pts": 1
    },
    {
     "pos": 6,
     "team": "Chihame All Stars",
     "p": 1,
     "w": 0,
     "d": 1,
     "l": 0,
     "f": 1,
     "a": 1,
     "gd": 0,
     "pts": 1
    },
    {
     "pos": 7,
     "team": "Ekwaiweni Tafika AS",
     "p": 1,
     "w": 0,
     "d": 1,
     "l": 0,
     "f": 1,
     "a": 1,
     "gd": 0,
     "pts": 1
    },
    {
     "pos": 8,
     "team": "Sporting FC",
     "p": 1,
     "w": 0,
     "d": 1,
     "l": 0,
     "f": 1,
     "a": 1,
     "gd": 0,
     "pts": 1
    },
    {
     "pos": 9,
     "team": "Chibavi Real Stars FC",
     "p": 1,
     "w": 0,
     "d": 1,
     "l": 0,
     "f": 0,
     "a": 0,
     "gd": 0,
     "pts": 1
    },
    {
     "pos": 10,
     "team": "Chirambo FC",
     "p": 1,
     "w": 0,
     "d": 1,
     "l": 0,
     "f": 0,
     "a": 0,
     "gd": 0,
     "pts": 1
    },
    {
     "pos": 11,
     "team": "Chipolopolo Boys FC",
     "p": 1,
     "w": 0,
     "d": 1,
     "l": 0,
     "f": 0,
     "a": 0,
     "gd": 0,
     "pts": 1
    },
    {
     "pos": 12,
     "team": "Ekwendeni United FC",
     "p": 1,
     "w": 0,
     "d": 1,
     "l": 0,
     "f": 0,
     "a": 0,
     "gd": 0,
     "pts": 1
    },
    {
     "pos": 13,
     "team": "Chisapa FC",
     "p": 1,
     "w": 0,
     "d": 0,
     "l": 1,
     "f": 1,
     "a": 2,
     "gd": -1,
     "pts": 0
    },
    {
     "pos": 14,
     "team": "Lube Masters FC",
     "p": 1,
     "w": 0,
     "d": 0,
     "l": 1,
     "f": 1,
     "a": 2,
     "gd": -1,
     "pts": 0
    },
    {
     "pos": 15,
     "team": "M'mbelwa Warriors FC",
     "p": 1,
     "w": 0,
     "d": 0,
     "l": 1,
     "f": 1,
     "a": 3,
     "gd": -2,
     "pts": 0
    },
    {
     "pos": 16,
     "team": "Chizumulu United FC",
     "p": 1,
     "w": 0,
     "d": 0,
     "l": 1,
     "f": 1,
     "a": 5,
     "gd": -4,
     "pts": 0
    }
   ],
   "notes": []
  },
  {
   "key": 2,
   "short": "2주차",
   "label": "2주차",
   "rows": [
    {
     "pos": 1,
     "team": "Simbowe Stars FC",
     "p": 2,
     "w": 2,
     "d": 0,
     "l": 0,
     "f": 6,
     "a": 1,
     "gd": 5,
     "pts": 6
    },
    {
     "pos": 2,
     "team": "Chibavi Real Stars FC",
     "p": 2,
     "w": 1,
     "d": 1,
     "l": 0,
     "f": 3,
     "a": 0,
     "gd": 3,
     "pts": 4
    },
    {
     "pos": 3,
     "team": "Sporting FC",
     "p": 2,
     "w": 1,
     "d": 1,
     "l": 0,
     "f": 3,
     "a": 1,
     "gd": 2,
     "pts": 4
    },
    {
     "pos": 4,
     "team": "Raiply FC",
     "p": 2,
     "w": 1,
     "d": 0,
     "l": 1,
     "f": 5,
     "a": 4,
     "gd": 1,
     "pts": 3
    },
    {
     "pos": 5,
     "team": "Embangweni United FC",
     "p": 1,
     "w": 1,
     "d": 0,
     "l": 0,
     "f": 2,
     "a": 1,
     "gd": 1,
     "pts": 3
    },
    {
     "pos": 6,
     "team": "M'mbelwa Warriors FC",
     "p": 2,
     "w": 1,
     "d": 0,
     "l": 1,
     "f": 4,
     "a": 4,
     "gd": 0,
     "pts": 3
    },
    {
     "pos": 7,
     "team": "Chisapa FC",
     "p": 2,
     "w": 1,
     "d": 0,
     "l": 1,
     "f": 2,
     "a": 2,
     "gd": 0,
     "pts": 3
    },
    {
     "pos": 8,
     "team": "Euthin Kuseli Veterans FC",
     "p": 2,
     "w": 1,
     "d": 0,
     "l": 1,
     "f": 2,
     "a": 4,
     "gd": -2,
     "pts": 3
    },
    {
     "pos": 9,
     "team": "Chizumulu United FC",
     "p": 2,
     "w": 1,
     "d": 0,
     "l": 1,
     "f": 2,
     "a": 5,
     "gd": -3,
     "pts": 3
    },
    {
     "pos": 10,
     "team": "Ekwaiweni Tafika AS",
     "p": 2,
     "w": 0,
     "d": 2,
     "l": 0,
     "f": 3,
     "a": 3,
     "gd": 0,
     "pts": 2
    },
    {
     "pos": 11,
     "team": "Ekwendeni United FC",
     "p": 1,
     "w": 0,
     "d": 1,
     "l": 0,
     "f": 0,
     "a": 0,
     "gd": 0,
     "pts": 1
    },
    {
     "pos": 12,
     "team": "Lube Masters FC",
     "p": 2,
     "w": 0,
     "d": 1,
     "l": 1,
     "f": 3,
     "a": 4,
     "gd": -1,
     "pts": 1
    },
    {
     "pos": 13,
     "team": "Ekwendeni Hardnockers FC",
     "p": 2,
     "w": 0,
     "d": 1,
     "l": 1,
     "f": 1,
     "a": 2,
     "gd": -1,
     "pts": 1
    },
    {
     "pos": 14,
     "team": "Chirambo FC",
     "p": 2,
     "w": 0,
     "d": 1,
     "l": 1,
     "f": 0,
     "a": 1,
     "gd": -1,
     "pts": 1
    },
    {
     "pos": 15,
     "team": "Chihame All Stars",
     "p": 2,
     "w": 0,
     "d": 1,
     "l": 1,
     "f": 2,
     "a": 4,
     "gd": -2,
     "pts": 1
    },
    {
     "pos": 16,
     "team": "Chipolopolo Boys FC",
     "p": 2,
     "w": 0,
     "d": 1,
     "l": 1,
     "f": 0,
     "a": 2,
     "gd": -2,
     "pts": 1
    }
   ],
   "notes": []
  },
  {
   "key": 3,
   "short": "3주차",
   "label": "3주차",
   "rows": [
    {
     "pos": 1,
     "team": "Simbowe Stars FC",
     "p": 3,
     "w": 2,
     "d": 1,
     "l": 0,
     "f": 7,
     "a": 2,
     "gd": 5,
     "pts": 7
    },
    {
     "pos": 2,
     "team": "Embangweni United FC",
     "p": 2,
     "w": 2,
     "d": 0,
     "l": 0,
     "f": 7,
     "a": 1,
     "gd": 6,
     "pts": 6
    },
    {
     "pos": 3,
     "team": "Sporting FC",
     "p": 3,
     "w": 1,
     "d": 2,
     "l": 0,
     "f": 3,
     "a": 1,
     "gd": 2,
     "pts": 5
    },
    {
     "pos": 4,
     "team": "Ekwaiweni Tafika AS",
     "p": 3,
     "w": 1,
     "d": 2,
     "l": 0,
     "f": 6,
     "a": 5,
     "gd": 1,
     "pts": 5
    },
    {
     "pos": 5,
     "team": "Chibavi Real Stars FC",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "f": 5,
     "a": 3,
     "gd": 2,
     "pts": 4
    },
    {
     "pos": 6,
     "team": "Raiply FC",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "f": 5,
     "a": 4,
     "gd": 1,
     "pts": 4
    },
    {
     "pos": 7,
     "team": "Lube Masters FC",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "f": 6,
     "a": 6,
     "gd": 0,
     "pts": 4
    },
    {
     "pos": 8,
     "team": "M'mbelwa Warriors FC",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "f": 5,
     "a": 5,
     "gd": 0,
     "pts": 4
    },
    {
     "pos": 9,
     "team": "Ekwendeni Hardnockers FC",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "f": 4,
     "a": 4,
     "gd": 0,
     "pts": 4
    },
    {
     "pos": 10,
     "team": "Chisapa FC",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "f": 3,
     "a": 3,
     "gd": 0,
     "pts": 4
    },
    {
     "pos": 11,
     "team": "Chihame All Stars",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "f": 5,
     "a": 6,
     "gd": -1,
     "pts": 4
    },
    {
     "pos": 12,
     "team": "Euthin Kuseli Veterans FC",
     "p": 3,
     "w": 1,
     "d": 0,
     "l": 2,
     "f": 4,
     "a": 7,
     "gd": -3,
     "pts": 3
    },
    {
     "pos": 13,
     "team": "Chizumulu United FC",
     "p": 3,
     "w": 1,
     "d": 0,
     "l": 2,
     "f": 4,
     "a": 8,
     "gd": -4,
     "pts": 3
    },
    {
     "pos": 14,
     "team": "Chipolopolo Boys FC",
     "p": 3,
     "w": 0,
     "d": 2,
     "l": 1,
     "f": 1,
     "a": 3,
     "gd": -2,
     "pts": 2
    },
    {
     "pos": 15,
     "team": "Ekwendeni United FC",
     "p": 2,
     "w": 0,
     "d": 1,
     "l": 1,
     "f": 2,
     "a": 3,
     "gd": -1,
     "pts": 1
    },
    {
     "pos": 16,
     "team": "Chirambo FC",
     "p": 3,
     "w": 0,
     "d": 1,
     "l": 2,
     "f": 0,
     "a": 6,
     "gd": -6,
     "pts": 1
    }
   ],
   "notes": []
  },
  {
   "key": 4,
   "short": "4주차",
   "label": "4주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 4,
     "w": 3,
     "d": 0,
     "l": 1,
     "f": 11,
     "a": 3,
     "gd": 8,
     "pts": 9
    },
    {
     "pos": 2,
     "team": "Simbowe Stars FC",
     "p": 4,
     "w": 2,
     "d": 2,
     "l": 0,
     "f": 8,
     "a": 3,
     "gd": 5,
     "pts": 8
    },
    {
     "pos": 3,
     "team": "M'mbelwa Warriors FC",
     "p": 4,
     "w": 2,
     "d": 1,
     "l": 1,
     "f": 7,
     "a": 5,
     "gd": 2,
     "pts": 7
    },
    {
     "pos": 4,
     "team": "Lube Masters FC",
     "p": 4,
     "w": 2,
     "d": 1,
     "l": 1,
     "f": 7,
     "a": 6,
     "gd": 1,
     "pts": 7
    },
    {
     "pos": 5,
     "team": "Chibavi Real Stars FC",
     "p": 4,
     "w": 1,
     "d": 2,
     "l": 1,
     "f": 6,
     "a": 4,
     "gd": 2,
     "pts": 5
    },
    {
     "pos": 6,
     "team": "Sporting FC",
     "p": 3,
     "w": 1,
     "d": 2,
     "l": 0,
     "f": 3,
     "a": 1,
     "gd": 2,
     "pts": 5
    },
    {
     "pos": 7,
     "team": "Ekwaiweni Tafika AS",
     "p": 3,
     "w": 1,
     "d": 2,
     "l": 0,
     "f": 6,
     "a": 5,
     "gd": 1,
     "pts": 5
    },
    {
     "pos": 8,
     "team": "Ekwendeni Hardnockers FC",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "f": 4,
     "a": 4,
     "gd": 0,
     "pts": 4
    },
    {
     "pos": 9,
     "team": "Ekwendeni United FC",
     "p": 4,
     "w": 1,
     "d": 1,
     "l": 2,
     "f": 4,
     "a": 4,
     "gd": 0,
     "pts": 4
    },
    {
     "pos": 10,
     "team": "Chisapa FC",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "f": 3,
     "a": 3,
     "gd": 0,
     "pts": 4
    },
    {
     "pos": 11,
     "team": "Raiply FC",
     "p": 4,
     "w": 1,
     "d": 1,
     "l": 2,
     "f": 5,
     "a": 6,
     "gd": -1,
     "pts": 4
    },
    {
     "pos": 12,
     "team": "Chihame All Stars",
     "p": 4,
     "w": 1,
     "d": 1,
     "l": 2,
     "f": 5,
     "a": 10,
     "gd": -5,
     "pts": 4
    },
    {
     "pos": 13,
     "team": "Euthin Kuseli Veterans FC",
     "p": 3,
     "w": 1,
     "d": 0,
     "l": 2,
     "f": 4,
     "a": 7,
     "gd": -3,
     "pts": 3
    },
    {
     "pos": 14,
     "team": "Chizumulu United FC",
     "p": 3,
     "w": 1,
     "d": 0,
     "l": 2,
     "f": 4,
     "a": 8,
     "gd": -4,
     "pts": 3
    },
    {
     "pos": 15,
     "team": "Chipolopolo Boys FC",
     "p": 3,
     "w": 0,
     "d": 2,
     "l": 1,
     "f": 1,
     "a": 3,
     "gd": -2,
     "pts": 2
    },
    {
     "pos": 16,
     "team": "Chirambo FC",
     "p": 3,
     "w": 0,
     "d": 1,
     "l": 2,
     "f": 0,
     "a": 6,
     "gd": -6,
     "pts": 1
    }
   ],
   "notes": []
  },
  {
   "key": 5,
   "short": "5주차",
   "label": "5주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 5,
     "w": 3,
     "d": 0,
     "l": 2,
     "f": 11,
     "a": 4,
     "gd": 7,
     "pts": 9
    },
    {
     "pos": 2,
     "team": "Simbowe Stars FC",
     "p": 5,
     "w": 2,
     "d": 3,
     "l": 0,
     "f": 8,
     "a": 3,
     "gd": 5,
     "pts": 9
    },
    {
     "pos": 3,
     "team": "Chibavi Real Stars FC",
     "p": 5,
     "w": 2,
     "d": 2,
     "l": 1,
     "f": 10,
     "a": 5,
     "gd": 5,
     "pts": 8
    },
    {
     "pos": 4,
     "team": "Ekwaiweni Tafika AS",
     "p": 4,
     "w": 2,
     "d": 2,
     "l": 0,
     "f": 10,
     "a": 7,
     "gd": 3,
     "pts": 8
    },
    {
     "pos": 5,
     "team": "Sporting FC",
     "p": 4,
     "w": 2,
     "d": 2,
     "l": 0,
     "f": 4,
     "a": 1,
     "gd": 3,
     "pts": 8
    },
    {
     "pos": 6,
     "team": "M'mbelwa Warriors FC",
     "p": 5,
     "w": 2,
     "d": 2,
     "l": 1,
     "f": 7,
     "a": 5,
     "gd": 2,
     "pts": 8
    },
    {
     "pos": 7,
     "team": "Raiply FC",
     "p": 5,
     "w": 2,
     "d": 1,
     "l": 2,
     "f": 11,
     "a": 8,
     "gd": 3,
     "pts": 7
    },
    {
     "pos": 8,
     "team": "Lube Masters FC",
     "p": 5,
     "w": 2,
     "d": 1,
     "l": 2,
     "f": 8,
     "a": 10,
     "gd": -2,
     "pts": 7
    },
    {
     "pos": 9,
     "team": "Ekwendeni United FC",
     "p": 5,
     "w": 1,
     "d": 2,
     "l": 2,
     "f": 4,
     "a": 4,
     "gd": 0,
     "pts": 5
    },
    {
     "pos": 10,
     "team": "Chihame All Stars",
     "p": 5,
     "w": 1,
     "d": 2,
     "l": 2,
     "f": 5,
     "a": 10,
     "gd": -5,
     "pts": 5
    },
    {
     "pos": 11,
     "team": "Chisapa FC",
     "p": 3,
     "w": 1,
     "d": 1,
     "l": 1,
     "f": 3,
     "a": 3,
     "gd": 0,
     "pts": 4
    },
    {
     "pos": 12,
     "team": "Chirambo FC",
     "p": 4,
     "w": 1,
     "d": 1,
     "l": 2,
     "f": 5,
     "a": 6,
     "gd": -1,
     "pts": 4
    },
    {
     "pos": 13,
     "team": "Ekwendeni Hardnockers FC",
     "p": 4,
     "w": 1,
     "d": 1,
     "l": 2,
     "f": 6,
     "a": 10,
     "gd": -4,
     "pts": 4
    },
    {
     "pos": 14,
     "team": "Chizumulu United FC",
     "p": 3,
     "w": 1,
     "d": 0,
     "l": 2,
     "f": 4,
     "a": 8,
     "gd": -4,
     "pts": 3
    },
    {
     "pos": 15,
     "team": "Euthin Kuseli Veterans FC",
     "p": 4,
     "w": 1,
     "d": 0,
     "l": 3,
     "f": 6,
     "a": 11,
     "gd": -5,
     "pts": 3
    },
    {
     "pos": 16,
     "team": "Chipolopolo Boys FC",
     "p": 4,
     "w": 0,
     "d": 2,
     "l": 2,
     "f": 1,
     "a": 8,
     "gd": -7,
     "pts": 2
    }
   ],
   "notes": []
  },
  {
   "key": 6,
   "short": "6주차",
   "label": "6주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 6,
     "w": 4,
     "d": 0,
     "l": 2,
     "f": 14,
     "a": 4,
     "gd": 10,
     "pts": 12
    },
    {
     "pos": 2,
     "team": "Sporting FC",
     "p": 5,
     "w": 3,
     "d": 2,
     "l": 0,
     "f": 9,
     "a": 2,
     "gd": 7,
     "pts": 11
    },
    {
     "pos": 3,
     "team": "Ekwaiweni Tafika AS",
     "p": 5,
     "w": 3,
     "d": 2,
     "l": 0,
     "f": 11,
     "a": 7,
     "gd": 4,
     "pts": 11
    },
    {
     "pos": 4,
     "team": "Simbowe Stars FC",
     "p": 6,
     "w": 2,
     "d": 4,
     "l": 0,
     "f": 8,
     "a": 3,
     "gd": 5,
     "pts": 10
    },
    {
     "pos": 5,
     "team": "Raiply FC",
     "p": 6,
     "w": 2,
     "d": 2,
     "l": 2,
     "f": 11,
     "a": 8,
     "gd": 3,
     "pts": 8
    },
    {
     "pos": 6,
     "team": "Chibavi Real Stars FC",
     "p": 6,
     "w": 2,
     "d": 2,
     "l": 2,
     "f": 10,
     "a": 8,
     "gd": 2,
     "pts": 8
    },
    {
     "pos": 7,
     "team": "M'mbelwa Warriors FC",
     "p": 5,
     "w": 2,
     "d": 2,
     "l": 1,
     "f": 7,
     "a": 5,
     "gd": 2,
     "pts": 8
    },
    {
     "pos": 8,
     "team": "Lube Masters FC",
     "p": 5,
     "w": 2,
     "d": 1,
     "l": 2,
     "f": 8,
     "a": 10,
     "gd": -2,
     "pts": 7
    },
    {
     "pos": 9,
     "team": "Chizumulu United FC",
     "p": 4,
     "w": 2,
     "d": 0,
     "l": 2,
     "f": 6,
     "a": 8,
     "gd": -2,
     "pts": 6
    },
    {
     "pos": 10,
     "team": "Chihame All Stars",
     "p": 6,
     "w": 1,
     "d": 3,
     "l": 2,
     "f": 5,
     "a": 10,
     "gd": -5,
     "pts": 6
    },
    {
     "pos": 11,
     "team": "Ekwendeni United FC",
     "p": 6,
     "w": 1,
     "d": 2,
     "l": 3,
     "f": 6,
     "a": 7,
     "gd": -1,
     "pts": 5
    },
    {
     "pos": 12,
     "team": "Ekwendeni Hardnockers FC",
     "p": 5,
     "w": 1,
     "d": 2,
     "l": 2,
     "f": 6,
     "a": 10,
     "gd": -4,
     "pts": 5
    },
    {
     "pos": 13,
     "team": "Chipolopolo Boys FC",
     "p": 5,
     "w": 1,
     "d": 2,
     "l": 2,
     "f": 4,
     "a": 10,
     "gd": -6,
     "pts": 5
    },
    {
     "pos": 14,
     "team": "Chisapa FC",
     "p": 5,
     "w": 1,
     "d": 1,
     "l": 3,
     "f": 3,
     "a": 6,
     "gd": -3,
     "pts": 4
    },
    {
     "pos": 15,
     "team": "Chirambo FC",
     "p": 5,
     "w": 1,
     "d": 1,
     "l": 3,
     "f": 6,
     "a": 11,
     "gd": -5,
     "pts": 4
    },
    {
     "pos": 16,
     "team": "Euthin Kuseli Veterans FC",
     "p": 4,
     "w": 1,
     "d": 0,
     "l": 3,
     "f": 6,
     "a": 11,
     "gd": -5,
     "pts": 3
    }
   ],
   "notes": []
  },
  {
   "key": 7,
   "short": "7주차",
   "label": "7주차",
   "rows": [
    {
     "pos": 1,
     "team": "M'mbelwa Warriors FC",
     "p": 7,
     "w": 4,
     "d": 2,
     "l": 1,
     "f": 11,
     "a": 6,
     "gd": 5,
     "pts": 14
    },
    {
     "pos": 2,
     "team": "Simbowe Stars FC",
     "p": 7,
     "w": 3,
     "d": 4,
     "l": 0,
     "f": 9,
     "a": 3,
     "gd": 6,
     "pts": 13
    },
    {
     "pos": 3,
     "team": "Embangweni United FC",
     "p": 7,
     "w": 4,
     "d": 0,
     "l": 3,
     "f": 14,
     "a": 5,
     "gd": 9,
     "pts": 12
    },
    {
     "pos": 4,
     "team": "Sporting FC",
     "p": 6,
     "w": 3,
     "d": 2,
     "l": 1,
     "f": 9,
     "a": 3,
     "gd": 6,
     "pts": 11
    },
    {
     "pos": 5,
     "team": "Ekwaiweni Tafika AS",
     "p": 6,
     "w": 3,
     "d": 2,
     "l": 1,
     "f": 11,
     "a": 8,
     "gd": 3,
     "pts": 11
    },
    {
     "pos": 6,
     "team": "Lube Masters FC",
     "p": 7,
     "w": 3,
     "d": 1,
     "l": 3,
     "f": 15,
     "a": 13,
     "gd": 2,
     "pts": 10
    },
    {
     "pos": 7,
     "team": "Raiply FC",
     "p": 7,
     "w": 2,
     "d": 3,
     "l": 2,
     "f": 13,
     "a": 10,
     "gd": 3,
     "pts": 9
    },
    {
     "pos": 8,
     "team": "Chihame All Stars",
     "p": 7,
     "w": 2,
     "d": 3,
     "l": 2,
     "f": 8,
     "a": 11,
     "gd": -3,
     "pts": 9
    },
    {
     "pos": 9,
     "team": "Chibavi Real Stars FC",
     "p": 7,
     "w": 2,
     "d": 2,
     "l": 3,
     "f": 11,
     "a": 11,
     "gd": 0,
     "pts": 8
    },
    {
     "pos": 10,
     "team": "Ekwendeni United FC",
     "p": 7,
     "w": 2,
     "d": 2,
     "l": 3,
     "f": 7,
     "a": 7,
     "gd": 0,
     "pts": 8
    },
    {
     "pos": 11,
     "team": "Euthin Kuseli Veterans FC",
     "p": 6,
     "w": 2,
     "d": 1,
     "l": 3,
     "f": 9,
     "a": 13,
     "gd": -4,
     "pts": 7
    },
    {
     "pos": 12,
     "team": "Chirambo FC",
     "p": 6,
     "w": 2,
     "d": 1,
     "l": 3,
     "f": 8,
     "a": 12,
     "gd": -4,
     "pts": 7
    },
    {
     "pos": 13,
     "team": "Ekwendeni Hardnockers FC",
     "p": 6,
     "w": 1,
     "d": 3,
     "l": 2,
     "f": 7,
     "a": 11,
     "gd": -4,
     "pts": 6
    },
    {
     "pos": 14,
     "team": "Chizumulu United FC",
     "p": 6,
     "w": 2,
     "d": 0,
     "l": 4,
     "f": 7,
     "a": 11,
     "gd": -4,
     "pts": 6
    },
    {
     "pos": 15,
     "team": "Chisapa FC",
     "p": 6,
     "w": 1,
     "d": 2,
     "l": 3,
     "f": 4,
     "a": 7,
     "gd": -3,
     "pts": 5
    },
    {
     "pos": 16,
     "team": "Chipolopolo Boys FC",
     "p": 6,
     "w": 1,
     "d": 2,
     "l": 3,
     "f": 4,
     "a": 16,
     "gd": -12,
     "pts": 5
    }
   ],
   "notes": []
  },
  {
   "key": 8,
   "short": "8주차",
   "label": "8주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 8,
     "w": 5,
     "d": 0,
     "l": 3,
     "f": 17,
     "a": 5,
     "gd": 12,
     "pts": 15
    },
    {
     "pos": 2,
     "team": "M'mbelwa Warriors FC",
     "p": 7,
     "w": 4,
     "d": 2,
     "l": 1,
     "f": 11,
     "a": 6,
     "gd": 5,
     "pts": 14
    },
    {
     "pos": 3,
     "team": "Simbowe Stars FC",
     "p": 8,
     "w": 3,
     "d": 4,
     "l": 1,
     "f": 11,
     "a": 6,
     "gd": 5,
     "pts": 13
    },
    {
     "pos": 4,
     "team": "Lube Masters FC",
     "p": 8,
     "w": 4,
     "d": 1,
     "l": 3,
     "f": 18,
     "a": 15,
     "gd": 3,
     "pts": 13
    },
    {
     "pos": 5,
     "team": "Sporting FC",
     "p": 6,
     "w": 3,
     "d": 2,
     "l": 1,
     "f": 9,
     "a": 3,
     "gd": 6,
     "pts": 11
    },
    {
     "pos": 6,
     "team": "Ekwaiweni Tafika AS",
     "p": 7,
     "w": 3,
     "d": 2,
     "l": 2,
     "f": 11,
     "a": 10,
     "gd": 1,
     "pts": 11
    },
    {
     "pos": 7,
     "team": "Raiply FC",
     "p": 8,
     "w": 2,
     "d": 4,
     "l": 2,
     "f": 13,
     "a": 10,
     "gd": 3,
     "pts": 10
    },
    {
     "pos": 8,
     "team": "Euthin Kuseli Veterans FC",
     "p": 7,
     "w": 3,
     "d": 1,
     "l": 3,
     "f": 11,
     "a": 13,
     "gd": -2,
     "pts": 10
    },
    {
     "pos": 9,
     "team": "Ekwendeni United FC",
     "p": 8,
     "w": 2,
     "d": 3,
     "l": 3,
     "f": 7,
     "a": 7,
     "gd": 0,
     "pts": 9
    },
    {
     "pos": 10,
     "team": "Chizumulu United FC",
     "p": 7,
     "w": 3,
     "d": 0,
     "l": 4,
     "f": 9,
     "a": 11,
     "gd": -2,
     "pts": 9
    },
    {
     "pos": 11,
     "team": "Chihame All Stars",
     "p": 8,
     "w": 2,
     "d": 3,
     "l": 3,
     "f": 8,
     "a": 13,
     "gd": -5,
     "pts": 9
    },
    {
     "pos": 12,
     "team": "Chibavi Real Stars FC",
     "p": 7,
     "w": 2,
     "d": 2,
     "l": 3,
     "f": 11,
     "a": 11,
     "gd": 0,
     "pts": 8
    },
    {
     "pos": 13,
     "team": "Chipolopolo Boys FC",
     "p": 7,
     "w": 2,
     "d": 2,
     "l": 3,
     "f": 6,
     "a": 16,
     "gd": -10,
     "pts": 8
    },
    {
     "pos": 14,
     "team": "Chirambo FC",
     "p": 6,
     "w": 2,
     "d": 1,
     "l": 3,
     "f": 8,
     "a": 12,
     "gd": -4,
     "pts": 7
    },
    {
     "pos": 15,
     "team": "Ekwendeni Hardnockers FC",
     "p": 7,
     "w": 1,
     "d": 3,
     "l": 3,
     "f": 7,
     "a": 13,
     "gd": -6,
     "pts": 6
    },
    {
     "pos": 16,
     "team": "Chisapa FC",
     "p": 7,
     "w": 1,
     "d": 2,
     "l": 4,
     "f": 4,
     "a": 10,
     "gd": -6,
     "pts": 5
    }
   ],
   "notes": []
  },
  {
   "key": 9,
   "short": "9주차",
   "label": "9주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 8,
     "w": 5,
     "d": 0,
     "l": 3,
     "f": 17,
     "a": 5,
     "gd": 12,
     "pts": 15
    },
    {
     "pos": 2,
     "team": "Sporting FC",
     "p": 8,
     "w": 4,
     "d": 3,
     "l": 1,
     "f": 14,
     "a": 6,
     "gd": 8,
     "pts": 15
    },
    {
     "pos": 3,
     "team": "Simbowe Stars FC",
     "p": 9,
     "w": 3,
     "d": 5,
     "l": 1,
     "f": 13,
     "a": 8,
     "gd": 5,
     "pts": 14
    },
    {
     "pos": 4,
     "team": "M'mbelwa Warriors FC",
     "p": 8,
     "w": 4,
     "d": 2,
     "l": 2,
     "f": 13,
     "a": 10,
     "gd": 3,
     "pts": 14
    },
    {
     "pos": 5,
     "team": "Ekwaiweni Tafika AS",
     "p": 8,
     "w": 4,
     "d": 2,
     "l": 2,
     "f": 12,
     "a": 10,
     "gd": 2,
     "pts": 14
    },
    {
     "pos": 6,
     "team": "Lube Masters FC",
     "p": 8,
     "w": 4,
     "d": 1,
     "l": 3,
     "f": 18,
     "a": 15,
     "gd": 3,
     "pts": 13
    },
    {
     "pos": 7,
     "team": "Chibavi Real Stars FC",
     "p": 9,
     "w": 3,
     "d": 3,
     "l": 3,
     "f": 16,
     "a": 13,
     "gd": 3,
     "pts": 12
    },
    {
     "pos": 8,
     "team": "Chihame All Stars",
     "p": 9,
     "w": 3,
     "d": 3,
     "l": 3,
     "f": 10,
     "a": 14,
     "gd": -4,
     "pts": 12
    },
    {
     "pos": 9,
     "team": "Raiply FC",
     "p": 8,
     "w": 2,
     "d": 4,
     "l": 2,
     "f": 13,
     "a": 10,
     "gd": 3,
     "pts": 10
    },
    {
     "pos": 10,
     "team": "Euthin Kuseli Veterans FC",
     "p": 8,
     "w": 3,
     "d": 1,
     "l": 4,
     "f": 12,
     "a": 17,
     "gd": -5,
     "pts": 10
    },
    {
     "pos": 11,
     "team": "Ekwendeni United FC",
     "p": 9,
     "w": 2,
     "d": 3,
     "l": 4,
     "f": 8,
     "a": 9,
     "gd": -1,
     "pts": 9
    },
    {
     "pos": 12,
     "team": "Chizumulu United FC",
     "p": 8,
     "w": 3,
     "d": 0,
     "l": 5,
     "f": 10,
     "a": 14,
     "gd": -4,
     "pts": 9
    },
    {
     "pos": 13,
     "team": "Ekwendeni Hardnockers FC",
     "p": 8,
     "w": 2,
     "d": 3,
     "l": 3,
     "f": 9,
     "a": 14,
     "gd": -5,
     "pts": 9
    },
    {
     "pos": 14,
     "team": "Chisapa FC",
     "p": 8,
     "w": 2,
     "d": 2,
     "l": 4,
     "f": 8,
     "a": 12,
     "gd": -4,
     "pts": 8
    },
    {
     "pos": 15,
     "team": "Chirambo FC",
     "p": 8,
     "w": 2,
     "d": 2,
     "l": 4,
     "f": 9,
     "a": 14,
     "gd": -5,
     "pts": 8
    },
    {
     "pos": 16,
     "team": "Chipolopolo Boys FC",
     "p": 8,
     "w": 2,
     "d": 2,
     "l": 4,
     "f": 7,
     "a": 18,
     "gd": -11,
     "pts": 8
    }
   ],
   "notes": []
  },
  {
   "key": 10,
   "short": "10주차",
   "label": "10주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 9,
     "w": 5,
     "d": 1,
     "l": 3,
     "f": 17,
     "a": 5,
     "gd": 12,
     "pts": 16
    },
    {
     "pos": 2,
     "team": "Sporting FC",
     "p": 9,
     "w": 4,
     "d": 4,
     "l": 1,
     "f": 16,
     "a": 8,
     "gd": 8,
     "pts": 16
    },
    {
     "pos": 3,
     "team": "Raiply FC",
     "p": 10,
     "w": 4,
     "d": 4,
     "l": 2,
     "f": 19,
     "a": 12,
     "gd": 7,
     "pts": 16
    },
    {
     "pos": 4,
     "team": "M'mbelwa Warriors FC",
     "p": 9,
     "w": 4,
     "d": 3,
     "l": 2,
     "f": 13,
     "a": 10,
     "gd": 3,
     "pts": 15
    },
    {
     "pos": 5,
     "team": "Chihame All Stars",
     "p": 10,
     "w": 4,
     "d": 3,
     "l": 3,
     "f": 12,
     "a": 15,
     "gd": -3,
     "pts": 15
    },
    {
     "pos": 6,
     "team": "Simbowe Stars FC",
     "p": 9,
     "w": 3,
     "d": 5,
     "l": 1,
     "f": 13,
     "a": 8,
     "gd": 5,
     "pts": 14
    },
    {
     "pos": 7,
     "team": "Ekwaiweni Tafika AS",
     "p": 9,
     "w": 4,
     "d": 2,
     "l": 3,
     "f": 13,
     "a": 12,
     "gd": 1,
     "pts": 14
    },
    {
     "pos": 8,
     "team": "Lube Masters FC",
     "p": 10,
     "w": 4,
     "d": 2,
     "l": 4,
     "f": 19,
     "a": 19,
     "gd": 0,
     "pts": 14
    },
    {
     "pos": 9,
     "team": "Chibavi Real Stars FC",
     "p": 10,
     "w": 3,
     "d": 4,
     "l": 3,
     "f": 18,
     "a": 15,
     "gd": 3,
     "pts": 13
    },
    {
     "pos": 10,
     "team": "Euthin Kuseli Veterans FC",
     "p": 9,
     "w": 3,
     "d": 2,
     "l": 4,
     "f": 12,
     "a": 17,
     "gd": -5,
     "pts": 11
    },
    {
     "pos": 11,
     "team": "Ekwendeni United FC",
     "p": 10,
     "w": 2,
     "d": 4,
     "l": 4,
     "f": 10,
     "a": 11,
     "gd": -1,
     "pts": 10
    },
    {
     "pos": 12,
     "team": "Ekwendeni Hardnockers FC",
     "p": 9,
     "w": 2,
     "d": 4,
     "l": 3,
     "f": 10,
     "a": 15,
     "gd": -5,
     "pts": 10
    },
    {
     "pos": 13,
     "team": "Chisapa FC",
     "p": 9,
     "w": 2,
     "d": 3,
     "l": 4,
     "f": 10,
     "a": 14,
     "gd": -4,
     "pts": 9
    },
    {
     "pos": 14,
     "team": "Chizumulu United FC",
     "p": 8,
     "w": 3,
     "d": 0,
     "l": 5,
     "f": 10,
     "a": 14,
     "gd": -4,
     "pts": 9
    },
    {
     "pos": 15,
     "team": "Chirambo FC",
     "p": 9,
     "w": 2,
     "d": 3,
     "l": 4,
     "f": 10,
     "a": 15,
     "gd": -5,
     "pts": 9
    },
    {
     "pos": 16,
     "team": "Chipolopolo Boys FC",
     "p": 9,
     "w": 2,
     "d": 2,
     "l": 5,
     "f": 8,
     "a": 20,
     "gd": -12,
     "pts": 8
    }
   ],
   "notes": []
  },
  {
   "key": 11,
   "short": "11주차",
   "label": "11주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 10,
     "w": 6,
     "d": 1,
     "l": 3,
     "f": 20,
     "a": 5,
     "gd": 15,
     "pts": 19
    },
    {
     "pos": 2,
     "team": "Raiply FC",
     "p": 11,
     "w": 5,
     "d": 4,
     "l": 2,
     "f": 24,
     "a": 14,
     "gd": 10,
     "pts": 19
    },
    {
     "pos": 3,
     "team": "Lube Masters FC",
     "p": 11,
     "w": 5,
     "d": 2,
     "l": 4,
     "f": 22,
     "a": 20,
     "gd": 2,
     "pts": 17
    },
    {
     "pos": 4,
     "team": "Ekwaiweni Tafika AS",
     "p": 10,
     "w": 5,
     "d": 2,
     "l": 3,
     "f": 14,
     "a": 12,
     "gd": 2,
     "pts": 17
    },
    {
     "pos": 5,
     "team": "Chibavi Real Stars FC",
     "p": 11,
     "w": 4,
     "d": 4,
     "l": 3,
     "f": 22,
     "a": 15,
     "gd": 7,
     "pts": 16
    },
    {
     "pos": 6,
     "team": "Sporting FC",
     "p": 10,
     "w": 4,
     "d": 4,
     "l": 2,
     "f": 18,
     "a": 11,
     "gd": 7,
     "pts": 16
    },
    {
     "pos": 7,
     "team": "M'mbelwa Warriors FC",
     "p": 10,
     "w": 4,
     "d": 3,
     "l": 3,
     "f": 13,
     "a": 14,
     "gd": -1,
     "pts": 15
    },
    {
     "pos": 8,
     "team": "Chihame All Stars",
     "p": 11,
     "w": 4,
     "d": 3,
     "l": 4,
     "f": 12,
     "a": 17,
     "gd": -5,
     "pts": 15
    },
    {
     "pos": 9,
     "team": "Simbowe Stars FC",
     "p": 10,
     "w": 3,
     "d": 5,
     "l": 2,
     "f": 14,
     "a": 10,
     "gd": 4,
     "pts": 14
    },
    {
     "pos": 10,
     "team": "Chisapa FC",
     "p": 10,
     "w": 3,
     "d": 3,
     "l": 4,
     "f": 13,
     "a": 16,
     "gd": -3,
     "pts": 12
    },
    {
     "pos": 11,
     "team": "Ekwendeni United FC",
     "p": 11,
     "w": 2,
     "d": 5,
     "l": 4,
     "f": 12,
     "a": 13,
     "gd": -1,
     "pts": 11
    },
    {
     "pos": 12,
     "team": "Euthin Kuseli Veterans FC",
     "p": 10,
     "w": 3,
     "d": 2,
     "l": 5,
     "f": 12,
     "a": 19,
     "gd": -7,
     "pts": 11
    },
    {
     "pos": 13,
     "team": "Chipolopolo Boys FC",
     "p": 10,
     "w": 3,
     "d": 2,
     "l": 5,
     "f": 10,
     "a": 20,
     "gd": -10,
     "pts": 11
    },
    {
     "pos": 14,
     "team": "Chizumulu United FC",
     "p": 9,
     "w": 3,
     "d": 1,
     "l": 5,
     "f": 12,
     "a": 16,
     "gd": -4,
     "pts": 10
    },
    {
     "pos": 15,
     "team": "Ekwendeni Hardnockers FC",
     "p": 10,
     "w": 2,
     "d": 4,
     "l": 4,
     "f": 10,
     "a": 18,
     "gd": -8,
     "pts": 10
    },
    {
     "pos": 16,
     "team": "Chirambo FC",
     "p": 10,
     "w": 2,
     "d": 3,
     "l": 5,
     "f": 12,
     "a": 20,
     "gd": -8,
     "pts": 9
    }
   ],
   "notes": []
  },
  {
   "key": 12,
   "short": "12주차",
   "label": "12주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 10,
     "w": 6,
     "d": 1,
     "l": 3,
     "f": 20,
     "a": 5,
     "gd": 15,
     "pts": 19
    },
    {
     "pos": 2,
     "team": "Raiply FC",
     "p": 11,
     "w": 5,
     "d": 4,
     "l": 2,
     "f": 24,
     "a": 14,
     "gd": 10,
     "pts": 19
    },
    {
     "pos": 3,
     "team": "Sporting FC",
     "p": 11,
     "w": 5,
     "d": 4,
     "l": 2,
     "f": 20,
     "a": 12,
     "gd": 8,
     "pts": 19
    },
    {
     "pos": 4,
     "team": "Simbowe Stars FC",
     "p": 11,
     "w": 4,
     "d": 5,
     "l": 2,
     "f": 20,
     "a": 11,
     "gd": 9,
     "pts": 17
    },
    {
     "pos": 5,
     "team": "Lube Masters FC",
     "p": 11,
     "w": 5,
     "d": 2,
     "l": 4,
     "f": 22,
     "a": 20,
     "gd": 2,
     "pts": 17
    },
    {
     "pos": 6,
     "team": "Ekwaiweni Tafika AS",
     "p": 11,
     "w": 5,
     "d": 2,
     "l": 4,
     "f": 15,
     "a": 14,
     "gd": 1,
     "pts": 17
    },
    {
     "pos": 7,
     "team": "Chibavi Real Stars FC",
     "p": 11,
     "w": 4,
     "d": 4,
     "l": 3,
     "f": 22,
     "a": 15,
     "gd": 7,
     "pts": 16
    },
    {
     "pos": 8,
     "team": "M'mbelwa Warriors FC",
     "p": 11,
     "w": 4,
     "d": 3,
     "l": 4,
     "f": 13,
     "a": 16,
     "gd": -3,
     "pts": 15
    },
    {
     "pos": 9,
     "team": "Chihame All Stars",
     "p": 11,
     "w": 4,
     "d": 3,
     "l": 4,
     "f": 12,
     "a": 17,
     "gd": -5,
     "pts": 15
    },
    {
     "pos": 10,
     "team": "Ekwendeni United FC",
     "p": 12,
     "w": 3,
     "d": 5,
     "l": 4,
     "f": 15,
     "a": 13,
     "gd": 2,
     "pts": 14
    },
    {
     "pos": 11,
     "team": "Ekwendeni Hardnockers FC",
     "p": 11,
     "w": 3,
     "d": 4,
     "l": 4,
     "f": 12,
     "a": 18,
     "gd": -6,
     "pts": 13
    },
    {
     "pos": 12,
     "team": "Chisapa FC",
     "p": 10,
     "w": 3,
     "d": 3,
     "l": 4,
     "f": 13,
     "a": 16,
     "gd": -3,
     "pts": 12
    },
    {
     "pos": 13,
     "team": "Chipolopolo Boys FC",
     "p": 12,
     "w": 3,
     "d": 3,
     "l": 6,
     "f": 15,
     "a": 30,
     "gd": -15,
     "pts": 12
    },
    {
     "pos": 14,
     "team": "Chizumulu United FC",
     "p": 10,
     "w": 3,
     "d": 2,
     "l": 5,
     "f": 16,
     "a": 20,
     "gd": -4,
     "pts": 11
    },
    {
     "pos": 15,
     "team": "Euthin Kuseli Veterans FC",
     "p": 11,
     "w": 3,
     "d": 2,
     "l": 6,
     "f": 12,
     "a": 22,
     "gd": -10,
     "pts": 11
    },
    {
     "pos": 16,
     "team": "Chirambo FC",
     "p": 10,
     "w": 2,
     "d": 3,
     "l": 5,
     "f": 12,
     "a": 20,
     "gd": -8,
     "pts": 9
    }
   ],
   "notes": []
  },
  {
   "key": 13,
   "short": "13주차",
   "label": "13주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 11,
     "w": 7,
     "d": 1,
     "l": 3,
     "f": 22,
     "a": 5,
     "gd": 17,
     "pts": 22
    },
    {
     "pos": 2,
     "team": "Raiply FC",
     "p": 12,
     "w": 6,
     "d": 4,
     "l": 2,
     "f": 27,
     "a": 15,
     "gd": 12,
     "pts": 22
    },
    {
     "pos": 3,
     "team": "Sporting FC",
     "p": 12,
     "w": 6,
     "d": 4,
     "l": 2,
     "f": 23,
     "a": 12,
     "gd": 11,
     "pts": 22
    },
    {
     "pos": 4,
     "team": "Lube Masters FC",
     "p": 12,
     "w": 6,
     "d": 2,
     "l": 4,
     "f": 24,
     "a": 21,
     "gd": 3,
     "pts": 20
    },
    {
     "pos": 5,
     "team": "Chibavi Real Stars FC",
     "p": 12,
     "w": 5,
     "d": 4,
     "l": 3,
     "f": 24,
     "a": 16,
     "gd": 8,
     "pts": 19
    },
    {
     "pos": 6,
     "team": "M'mbelwa Warriors FC",
     "p": 12,
     "w": 5,
     "d": 3,
     "l": 4,
     "f": 17,
     "a": 17,
     "gd": 0,
     "pts": 18
    },
    {
     "pos": 7,
     "team": "Chihame All Stars",
     "p": 12,
     "w": 5,
     "d": 3,
     "l": 4,
     "f": 13,
     "a": 17,
     "gd": -4,
     "pts": 18
    },
    {
     "pos": 8,
     "team": "Simbowe Stars FC",
     "p": 12,
     "w": 4,
     "d": 5,
     "l": 3,
     "f": 21,
     "a": 13,
     "gd": 8,
     "pts": 17
    },
    {
     "pos": 9,
     "team": "Ekwaiweni Tafika AS",
     "p": 12,
     "w": 5,
     "d": 2,
     "l": 5,
     "f": 16,
     "a": 17,
     "gd": -1,
     "pts": 17
    },
    {
     "pos": 10,
     "team": "Ekwendeni United FC",
     "p": 13,
     "w": 3,
     "d": 5,
     "l": 5,
     "f": 16,
     "a": 15,
     "gd": 1,
     "pts": 14
    },
    {
     "pos": 11,
     "team": "Chizumulu United FC",
     "p": 11,
     "w": 4,
     "d": 2,
     "l": 5,
     "f": 18,
     "a": 21,
     "gd": -3,
     "pts": 14
    },
    {
     "pos": 12,
     "team": "Ekwendeni Hardnockers FC",
     "p": 12,
     "w": 3,
     "d": 4,
     "l": 5,
     "f": 12,
     "a": 21,
     "gd": -9,
     "pts": 13
    },
    {
     "pos": 13,
     "team": "Chisapa FC",
     "p": 11,
     "w": 3,
     "d": 3,
     "l": 5,
     "f": 13,
     "a": 17,
     "gd": -4,
     "pts": 12
    },
    {
     "pos": 14,
     "team": "Chipolopolo Boys FC",
     "p": 13,
     "w": 3,
     "d": 3,
     "l": 7,
     "f": 15,
     "a": 32,
     "gd": -17,
     "pts": 12
    },
    {
     "pos": 15,
     "team": "Euthin Kuseli Veterans FC",
     "p": 12,
     "w": 3,
     "d": 2,
     "l": 7,
     "f": 13,
     "a": 26,
     "gd": -13,
     "pts": 11
    },
    {
     "pos": 16,
     "team": "Chirambo FC",
     "p": 11,
     "w": 2,
     "d": 3,
     "l": 6,
     "f": 13,
     "a": 22,
     "gd": -9,
     "pts": 9
    }
   ],
   "notes": [
    "득실차 수정: Euthin Kuseli Veterans FC -3→-13 (득-실 기준)"
   ]
  },
  {
   "key": 14,
   "short": "14주차",
   "label": "14주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 12,
     "w": 8,
     "d": 1,
     "l": 3,
     "f": 23,
     "a": 5,
     "gd": 18,
     "pts": 25
    },
    {
     "pos": 2,
     "team": "Raiply FC",
     "p": 13,
     "w": 7,
     "d": 4,
     "l": 2,
     "f": 30,
     "a": 16,
     "gd": 14,
     "pts": 25
    },
    {
     "pos": 3,
     "team": "Sporting FC",
     "p": 13,
     "w": 7,
     "d": 4,
     "l": 2,
     "f": 25,
     "a": 13,
     "gd": 12,
     "pts": 25
    },
    {
     "pos": 4,
     "team": "Simbowe Stars FC",
     "p": 13,
     "w": 5,
     "d": 5,
     "l": 3,
     "f": 23,
     "a": 13,
     "gd": 10,
     "pts": 20
    },
    {
     "pos": 5,
     "team": "Chibavi Real Stars FC",
     "p": 13,
     "w": 5,
     "d": 5,
     "l": 3,
     "f": 26,
     "a": 18,
     "gd": 8,
     "pts": 20
    },
    {
     "pos": 6,
     "team": "Lube Masters FC",
     "p": 12,
     "w": 6,
     "d": 2,
     "l": 4,
     "f": 24,
     "a": 21,
     "gd": 3,
     "pts": 20
    },
    {
     "pos": 7,
     "team": "M'mbelwa Warriors FC",
     "p": 13,
     "w": 5,
     "d": 3,
     "l": 5,
     "f": 18,
     "a": 19,
     "gd": -1,
     "pts": 18
    },
    {
     "pos": 8,
     "team": "Chihame All Stars",
     "p": 13,
     "w": 5,
     "d": 3,
     "l": 5,
     "f": 13,
     "a": 19,
     "gd": -6,
     "pts": 18
    },
    {
     "pos": 9,
     "team": "Ekwaiweni Tafika AS",
     "p": 13,
     "w": 5,
     "d": 2,
     "l": 6,
     "f": 16,
     "a": 18,
     "gd": -2,
     "pts": 17
    },
    {
     "pos": 10,
     "team": "Ekwendeni Hardnockers FC",
     "p": 13,
     "w": 4,
     "d": 4,
     "l": 5,
     "f": 14,
     "a": 21,
     "gd": -7,
     "pts": 16
    },
    {
     "pos": 11,
     "team": "Chizumulu United FC",
     "p": 12,
     "w": 4,
     "d": 3,
     "l": 5,
     "f": 20,
     "a": 23,
     "gd": -3,
     "pts": 15
    },
    {
     "pos": 12,
     "team": "Chipolopolo Boys FC",
     "p": 14,
     "w": 4,
     "d": 3,
     "l": 7,
     "f": 17,
     "a": 33,
     "gd": -16,
     "pts": 15
    },
    {
     "pos": 13,
     "team": "Ekwendeni United FC",
     "p": 13,
     "w": 3,
     "d": 5,
     "l": 5,
     "f": 16,
     "a": 15,
     "gd": 1,
     "pts": 14
    },
    {
     "pos": 14,
     "team": "Chisapa FC",
     "p": 13,
     "w": 3,
     "d": 3,
     "l": 7,
     "f": 15,
     "a": 22,
     "gd": -7,
     "pts": 12
    },
    {
     "pos": 15,
     "team": "Euthin Kuseli Veterans FC",
     "p": 12,
     "w": 3,
     "d": 2,
     "l": 7,
     "f": 13,
     "a": 26,
     "gd": -13,
     "pts": 11
    },
    {
     "pos": 16,
     "team": "Chirambo FC",
     "p": 12,
     "w": 2,
     "d": 3,
     "l": 7,
     "f": 13,
     "a": 24,
     "gd": -11,
     "pts": 9
    }
   ],
   "notes": []
  },
  {
   "key": 15,
   "short": "15주차",
   "label": "15주차",
   "rows": [
    {
     "pos": 1,
     "team": "Raiply FC",
     "p": 14,
     "w": 8,
     "d": 4,
     "l": 2,
     "f": 33,
     "a": 16,
     "gd": 17,
     "pts": 28
    },
    {
     "pos": 2,
     "team": "Embangweni United FC",
     "p": 13,
     "w": 8,
     "d": 1,
     "l": 4,
     "f": 24,
     "a": 7,
     "gd": 17,
     "pts": 25
    },
    {
     "pos": 3,
     "team": "Sporting FC",
     "p": 14,
     "w": 7,
     "d": 4,
     "l": 3,
     "f": 25,
     "a": 14,
     "gd": 11,
     "pts": 25
    },
    {
     "pos": 4,
     "team": "Chibavi Real Stars FC",
     "p": 14,
     "w": 6,
     "d": 5,
     "l": 3,
     "f": 32,
     "a": 19,
     "gd": 13,
     "pts": 23
    },
    {
     "pos": 5,
     "team": "Simbowe Stars FC",
     "p": 15,
     "w": 6,
     "d": 5,
     "l": 4,
     "f": 27,
     "a": 17,
     "gd": 10,
     "pts": 23
    },
    {
     "pos": 6,
     "team": "Lube Masters FC",
     "p": 13,
     "w": 7,
     "d": 2,
     "l": 4,
     "f": 25,
     "a": 21,
     "gd": 4,
     "pts": 23
    },
    {
     "pos": 7,
     "team": "M'mbelwa Warriors FC",
     "p": 14,
     "w": 6,
     "d": 3,
     "l": 5,
     "f": 21,
     "a": 21,
     "gd": 0,
     "pts": 21
    },
    {
     "pos": 8,
     "team": "Ekwaiweni Tafika AS",
     "p": 14,
     "w": 6,
     "d": 2,
     "l": 6,
     "f": 20,
     "a": 19,
     "gd": 1,
     "pts": 20
    },
    {
     "pos": 9,
     "team": "Ekwendeni Hardnockers FC",
     "p": 14,
     "w": 5,
     "d": 4,
     "l": 5,
     "f": 15,
     "a": 21,
     "gd": -6,
     "pts": 19
    },
    {
     "pos": 10,
     "team": "Chizumulu United FC",
     "p": 14,
     "w": 5,
     "d": 3,
     "l": 6,
     "f": 23,
     "a": 28,
     "gd": -5,
     "pts": 18
    },
    {
     "pos": 11,
     "team": "Chihame All Stars",
     "p": 13,
     "w": 5,
     "d": 3,
     "l": 5,
     "f": 13,
     "a": 19,
     "gd": -6,
     "pts": 18
    },
    {
     "pos": 12,
     "team": "Chipolopolo Boys FC",
     "p": 15,
     "w": 4,
     "d": 3,
     "l": 8,
     "f": 17,
     "a": 34,
     "gd": -17,
     "pts": 15
    },
    {
     "pos": 13,
     "team": "Ekwendeni United FC",
     "p": 14,
     "w": 3,
     "d": 5,
     "l": 6,
     "f": 17,
     "a": 19,
     "gd": -2,
     "pts": 14
    },
    {
     "pos": 14,
     "team": "Chisapa FC",
     "p": 14,
     "w": 3,
     "d": 3,
     "l": 8,
     "f": 16,
     "a": 28,
     "gd": -12,
     "pts": 12
    },
    {
     "pos": 15,
     "team": "Euthin Kuseli Veterans FC",
     "p": 13,
     "w": 3,
     "d": 3,
     "l": 7,
     "f": 15,
     "a": 28,
     "gd": -13,
     "pts": 12
    },
    {
     "pos": 16,
     "team": "Chirambo FC",
     "p": 14,
     "w": 2,
     "d": 4,
     "l": 8,
     "f": 17,
     "a": 29,
     "gd": -12,
     "pts": 10
    }
   ],
   "notes": []
  },
  {
   "key": 16,
   "short": "16주차",
   "label": "16주차",
   "rows": [
    {
     "pos": 1,
     "team": "Raiply FC",
     "p": 14,
     "w": 8,
     "d": 4,
     "l": 2,
     "f": 33,
     "a": 16,
     "gd": 17,
     "pts": 28
    },
    {
     "pos": 2,
     "team": "Sporting FC",
     "p": 15,
     "w": 7,
     "d": 5,
     "l": 3,
     "f": 26,
     "a": 15,
     "gd": 11,
     "pts": 26
    },
    {
     "pos": 3,
     "team": "Embangweni United FC",
     "p": 13,
     "w": 8,
     "d": 1,
     "l": 4,
     "f": 24,
     "a": 7,
     "gd": 17,
     "pts": 25
    },
    {
     "pos": 4,
     "team": "Lube Masters FC",
     "p": 14,
     "w": 7,
     "d": 3,
     "l": 4,
     "f": 28,
     "a": 24,
     "gd": 4,
     "pts": 24
    },
    {
     "pos": 5,
     "team": "Chibavi Real Stars FC",
     "p": 14,
     "w": 6,
     "d": 5,
     "l": 3,
     "f": 32,
     "a": 19,
     "gd": 13,
     "pts": 23
    },
    {
     "pos": 6,
     "team": "Simbowe Stars FC",
     "p": 15,
     "w": 6,
     "d": 5,
     "l": 4,
     "f": 27,
     "a": 17,
     "gd": 10,
     "pts": 23
    },
    {
     "pos": 7,
     "team": "M'mbelwa Warriors FC",
     "p": 14,
     "w": 6,
     "d": 3,
     "l": 5,
     "f": 21,
     "a": 21,
     "gd": 0,
     "pts": 21
    },
    {
     "pos": 8,
     "team": "Ekwaiweni Tafika AS",
     "p": 14,
     "w": 6,
     "d": 2,
     "l": 6,
     "f": 20,
     "a": 19,
     "gd": 1,
     "pts": 20
    },
    {
     "pos": 9,
     "team": "Ekwendeni Hardnockers FC",
     "p": 14,
     "w": 5,
     "d": 4,
     "l": 5,
     "f": 15,
     "a": 21,
     "gd": -6,
     "pts": 19
    },
    {
     "pos": 10,
     "team": "Chihame All Stars",
     "p": 14,
     "w": 5,
     "d": 4,
     "l": 5,
     "f": 14,
     "a": 20,
     "gd": -6,
     "pts": 19
    },
    {
     "pos": 11,
     "team": "Chizumulu United FC",
     "p": 14,
     "w": 5,
     "d": 3,
     "l": 6,
     "f": 23,
     "a": 28,
     "gd": -5,
     "pts": 18
    },
    {
     "pos": 12,
     "team": "Ekwendeni United FC",
     "p": 15,
     "w": 3,
     "d": 6,
     "l": 6,
     "f": 18,
     "a": 20,
     "gd": -2,
     "pts": 15
    },
    {
     "pos": 13,
     "team": "Chipolopolo Boys FC",
     "p": 15,
     "w": 4,
     "d": 3,
     "l": 8,
     "f": 17,
     "a": 34,
     "gd": -17,
     "pts": 15
    },
    {
     "pos": 14,
     "team": "Chisapa FC",
     "p": 15,
     "w": 3,
     "d": 4,
     "l": 8,
     "f": 19,
     "a": 31,
     "gd": -12,
     "pts": 13
    },
    {
     "pos": 15,
     "team": "Euthin Kuseli Veterans FC",
     "p": 14,
     "w": 3,
     "d": 4,
     "l": 7,
     "f": 16,
     "a": 29,
     "gd": -13,
     "pts": 13
    },
    {
     "pos": 16,
     "team": "Chirambo FC",
     "p": 14,
     "w": 2,
     "d": 4,
     "l": 8,
     "f": 17,
     "a": 29,
     "gd": -12,
     "pts": 10
    }
   ],
   "notes": []
  },
  {
   "key": 17,
   "short": "17주차",
   "label": "17주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 14,
     "w": 9,
     "d": 1,
     "l": 4,
     "f": 28,
     "a": 7,
     "gd": 21,
     "pts": 28
    },
    {
     "pos": 2,
     "team": "Raiply FC",
     "p": 14,
     "w": 8,
     "d": 4,
     "l": 2,
     "f": 33,
     "a": 16,
     "gd": 17,
     "pts": 28
    },
    {
     "pos": 3,
     "team": "Lube Masters FC",
     "p": 15,
     "w": 8,
     "d": 3,
     "l": 4,
     "f": 31,
     "a": 26,
     "gd": 5,
     "pts": 27
    },
    {
     "pos": 4,
     "team": "Chibavi Real Stars FC",
     "p": 15,
     "w": 7,
     "d": 5,
     "l": 3,
     "f": 37,
     "a": 21,
     "gd": 16,
     "pts": 26
    },
    {
     "pos": 5,
     "team": "Sporting FC",
     "p": 15,
     "w": 7,
     "d": 5,
     "l": 3,
     "f": 26,
     "a": 15,
     "gd": 11,
     "pts": 26
    },
    {
     "pos": 6,
     "team": "Simbowe Stars FC",
     "p": 15,
     "w": 6,
     "d": 5,
     "l": 4,
     "f": 27,
     "a": 17,
     "gd": 10,
     "pts": 23
    },
    {
     "pos": 7,
     "team": "M'mbelwa Warriors FC",
     "p": 14,
     "w": 6,
     "d": 3,
     "l": 5,
     "f": 21,
     "a": 21,
     "gd": 0,
     "pts": 21
    },
    {
     "pos": 8,
     "team": "Ekwaiweni Tafika AS",
     "p": 15,
     "w": 6,
     "d": 2,
     "l": 7,
     "f": 22,
     "a": 24,
     "gd": -2,
     "pts": 20
    },
    {
     "pos": 9,
     "team": "Ekwendeni Hardnockers FC",
     "p": 15,
     "w": 5,
     "d": 4,
     "l": 6,
     "f": 17,
     "a": 24,
     "gd": -7,
     "pts": 19
    },
    {
     "pos": 10,
     "team": "Chihame All Stars",
     "p": 15,
     "w": 5,
     "d": 4,
     "l": 6,
     "f": 15,
     "a": 22,
     "gd": -7,
     "pts": 19
    },
    {
     "pos": 11,
     "team": "Chizumulu United FC",
     "p": 14,
     "w": 5,
     "d": 3,
     "l": 6,
     "f": 23,
     "a": 28,
     "gd": -5,
     "pts": 18
    },
    {
     "pos": 12,
     "team": "Ekwendeni United FC",
     "p": 15,
     "w": 3,
     "d": 6,
     "l": 6,
     "f": 18,
     "a": 20,
     "gd": -2,
     "pts": 15
    },
    {
     "pos": 13,
     "team": "Chipolopolo Boys FC",
     "p": 15,
     "w": 4,
     "d": 3,
     "l": 8,
     "f": 17,
     "a": 34,
     "gd": -17,
     "pts": 15
    },
    {
     "pos": 14,
     "team": "Chirambo FC",
     "p": 15,
     "w": 3,
     "d": 4,
     "l": 8,
     "f": 19,
     "a": 30,
     "gd": -11,
     "pts": 13
    },
    {
     "pos": 15,
     "team": "Chisapa FC",
     "p": 15,
     "w": 3,
     "d": 4,
     "l": 8,
     "f": 19,
     "a": 31,
     "gd": -12,
     "pts": 13
    },
    {
     "pos": 16,
     "team": "Euthin Kuseli Veterans FC",
     "p": 15,
     "w": 3,
     "d": 4,
     "l": 8,
     "f": 16,
     "a": 33,
     "gd": -17,
     "pts": 13
    }
   ],
   "notes": [
    "수정: Embangweni 패 3→4, Ekwaiweni Tafika 무 3→2, Chipolopolo 득점 16→17 (경기수·승점·득실차 기준 재계산)"
   ]
  },
  {
   "key": 18,
   "short": "전반기 종료",
   "label": "전반기 종료 - End of first round (팀당 15경기)",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 15,
     "w": 10,
     "d": 1,
     "l": 4,
     "f": 29,
     "a": 7,
     "gd": 22,
     "pts": 31
    },
    {
     "pos": 2,
     "team": "Raiply FC",
     "p": 15,
     "w": 8,
     "d": 4,
     "l": 3,
     "f": 33,
     "a": 17,
     "gd": 16,
     "pts": 28
    },
    {
     "pos": 3,
     "team": "Lube Masters FC",
     "p": 15,
     "w": 8,
     "d": 3,
     "l": 4,
     "f": 31,
     "a": 26,
     "gd": 5,
     "pts": 27
    },
    {
     "pos": 4,
     "team": "Chibavi Real Stars FC",
     "p": 15,
     "w": 7,
     "d": 5,
     "l": 3,
     "f": 37,
     "a": 21,
     "gd": 16,
     "pts": 26
    },
    {
     "pos": 5,
     "team": "Sporting FC",
     "p": 15,
     "w": 7,
     "d": 5,
     "l": 3,
     "f": 26,
     "a": 15,
     "gd": 11,
     "pts": 26
    },
    {
     "pos": 6,
     "team": "M'mbelwa Warriors FC",
     "p": 15,
     "w": 7,
     "d": 3,
     "l": 5,
     "f": 24,
     "a": 23,
     "gd": 1,
     "pts": 24
    },
    {
     "pos": 7,
     "team": "Simbowe Stars FC",
     "p": 15,
     "w": 6,
     "d": 5,
     "l": 4,
     "f": 27,
     "a": 17,
     "gd": 10,
     "pts": 23
    },
    {
     "pos": 8,
     "team": "Ekwaiweni Tafika AS",
     "p": 15,
     "w": 6,
     "d": 2,
     "l": 7,
     "f": 22,
     "a": 24,
     "gd": -2,
     "pts": 20
    },
    {
     "pos": 9,
     "team": "Ekwendeni Hardnockers FC",
     "p": 15,
     "w": 5,
     "d": 4,
     "l": 6,
     "f": 17,
     "a": 24,
     "gd": -7,
     "pts": 19
    },
    {
     "pos": 10,
     "team": "Chihame All Stars",
     "p": 15,
     "w": 5,
     "d": 4,
     "l": 6,
     "f": 15,
     "a": 22,
     "gd": -7,
     "pts": 19
    },
    {
     "pos": 11,
     "team": "Chizumulu United FC",
     "p": 15,
     "w": 5,
     "d": 3,
     "l": 7,
     "f": 25,
     "a": 31,
     "gd": -6,
     "pts": 18
    },
    {
     "pos": 12,
     "team": "Ekwendeni United FC",
     "p": 15,
     "w": 3,
     "d": 6,
     "l": 6,
     "f": 18,
     "a": 20,
     "gd": -2,
     "pts": 15
    },
    {
     "pos": 13,
     "team": "Chipolopolo Boys FC",
     "p": 15,
     "w": 4,
     "d": 3,
     "l": 8,
     "f": 17,
     "a": 34,
     "gd": -17,
     "pts": 15
    },
    {
     "pos": 14,
     "team": "Chirambo FC",
     "p": 15,
     "w": 3,
     "d": 4,
     "l": 8,
     "f": 19,
     "a": 30,
     "gd": -11,
     "pts": 13
    },
    {
     "pos": 15,
     "team": "Chisapa FC",
     "p": 15,
     "w": 3,
     "d": 4,
     "l": 8,
     "f": 19,
     "a": 31,
     "gd": -12,
     "pts": 13
    },
    {
     "pos": 16,
     "team": "Euthin Kuseli Veterans FC",
     "p": 15,
     "w": 3,
     "d": 4,
     "l": 8,
     "f": 16,
     "a": 33,
     "gd": -17,
     "pts": 13
    }
   ],
   "notes": [
    "승(W) 수정: Chibavi 8→7, Simbowe 7→6, Ekwendeni Hardnockers 6→5, Ekwendeni United 5→3, Chipolopolo 3→4, Chirambo 4→3 (경기수·승점 기준 재계산)"
   ]
  },
  {
   "key": 19,
   "short": "후반기 16주차",
   "label": "후반기 16주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 16,
     "w": 11,
     "d": 1,
     "l": 4,
     "f": 32,
     "a": 9,
     "gd": 23,
     "pts": 34
    },
    {
     "pos": 2,
     "team": "Sporting FC",
     "p": 16,
     "w": 8,
     "d": 5,
     "l": 3,
     "f": 33,
     "a": 16,
     "gd": 17,
     "pts": 29
    },
    {
     "pos": 3,
     "team": "Raiply FC",
     "p": 15,
     "w": 8,
     "d": 4,
     "l": 3,
     "f": 33,
     "a": 17,
     "gd": 16,
     "pts": 28
    },
    {
     "pos": 4,
     "team": "Lube Masters FC",
     "p": 16,
     "w": 8,
     "d": 3,
     "l": 5,
     "f": 33,
     "a": 29,
     "gd": 4,
     "pts": 27
    },
    {
     "pos": 5,
     "team": "M'mbelwa Warriors FC",
     "p": 16,
     "w": 8,
     "d": 3,
     "l": 5,
     "f": 26,
     "a": 23,
     "gd": 3,
     "pts": 27
    },
    {
     "pos": 6,
     "team": "Chibavi Real Stars FC",
     "p": 15,
     "w": 7,
     "d": 5,
     "l": 3,
     "f": 37,
     "a": 21,
     "gd": 16,
     "pts": 26
    },
    {
     "pos": 7,
     "team": "Simbowe Stars FC",
     "p": 16,
     "w": 6,
     "d": 5,
     "l": 5,
     "f": 27,
     "a": 19,
     "gd": 8,
     "pts": 23
    },
    {
     "pos": 8,
     "team": "Ekwaiweni Tafika AS",
     "p": 15,
     "w": 6,
     "d": 2,
     "l": 7,
     "f": 22,
     "a": 24,
     "gd": -2,
     "pts": 20
    },
    {
     "pos": 9,
     "team": "Ekwendeni Hardnockers FC",
     "p": 15,
     "w": 5,
     "d": 4,
     "l": 6,
     "f": 17,
     "a": 24,
     "gd": -7,
     "pts": 19
    },
    {
     "pos": 10,
     "team": "Chihame All Stars",
     "p": 16,
     "w": 5,
     "d": 4,
     "l": 7,
     "f": 16,
     "a": 29,
     "gd": -13,
     "pts": 19
    },
    {
     "pos": 11,
     "team": "Ekwendeni United FC",
     "p": 16,
     "w": 4,
     "d": 6,
     "l": 6,
     "f": 22,
     "a": 20,
     "gd": 2,
     "pts": 18
    },
    {
     "pos": 12,
     "team": "Chizumulu United FC",
     "p": 15,
     "w": 5,
     "d": 3,
     "l": 7,
     "f": 25,
     "a": 31,
     "gd": -6,
     "pts": 18
    },
    {
     "pos": 13,
     "team": "Chipolopolo Boys FC",
     "p": 15,
     "w": 4,
     "d": 3,
     "l": 8,
     "f": 17,
     "a": 34,
     "gd": -17,
     "pts": 15
    },
    {
     "pos": 14,
     "team": "Chisapa FC",
     "p": 16,
     "w": 3,
     "d": 5,
     "l": 8,
     "f": 19,
     "a": 31,
     "gd": -12,
     "pts": 14
    },
    {
     "pos": 15,
     "team": "Euthin Kuseli Veterans FC",
     "p": 16,
     "w": 3,
     "d": 5,
     "l": 8,
     "f": 16,
     "a": 33,
     "gd": -17,
     "pts": 14
    },
    {
     "pos": 16,
     "team": "Chirambo FC",
     "p": 16,
     "w": 3,
     "d": 4,
     "l": 9,
     "f": 19,
     "a": 34,
     "gd": -15,
     "pts": 13
    }
   ],
   "notes": [
    "수정: Chirambo 패 8→9"
   ]
  },
  {
   "key": 20,
   "short": "후반기 17주차",
   "label": "후반기 17주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 17,
     "w": 12,
     "d": 1,
     "l": 4,
     "f": 35,
     "a": 9,
     "gd": 26,
     "pts": 37
    },
    {
     "pos": 2,
     "team": "Raiply FC",
     "p": 16,
     "w": 9,
     "d": 4,
     "l": 3,
     "f": 36,
     "a": 17,
     "gd": 19,
     "pts": 31
    },
    {
     "pos": 3,
     "team": "Lube Masters FC",
     "p": 17,
     "w": 9,
     "d": 3,
     "l": 5,
     "f": 35,
     "a": 29,
     "gd": 6,
     "pts": 30
    },
    {
     "pos": 4,
     "team": "Sporting FC",
     "p": 17,
     "w": 8,
     "d": 5,
     "l": 4,
     "f": 34,
     "a": 18,
     "gd": 16,
     "pts": 29
    },
    {
     "pos": 5,
     "team": "M'mbelwa Warriors FC",
     "p": 17,
     "w": 8,
     "d": 3,
     "l": 6,
     "f": 27,
     "a": 27,
     "gd": 0,
     "pts": 27
    },
    {
     "pos": 6,
     "team": "Chibavi Real Stars FC",
     "p": 16,
     "w": 7,
     "d": 5,
     "l": 4,
     "f": 37,
     "a": 24,
     "gd": 13,
     "pts": 26
    },
    {
     "pos": 7,
     "team": "Simbowe Stars FC",
     "p": 17,
     "w": 7,
     "d": 5,
     "l": 5,
     "f": 29,
     "a": 20,
     "gd": 9,
     "pts": 26
    },
    {
     "pos": 8,
     "team": "Chihame All Stars",
     "p": 17,
     "w": 6,
     "d": 4,
     "l": 7,
     "f": 20,
     "a": 30,
     "gd": -10,
     "pts": 22
    },
    {
     "pos": 9,
     "team": "Ekwaiweni Tafika AS",
     "p": 16,
     "w": 6,
     "d": 2,
     "l": 8,
     "f": 22,
     "a": 26,
     "gd": -4,
     "pts": 20
    },
    {
     "pos": 10,
     "team": "Ekwendeni Hardnockers FC",
     "p": 15,
     "w": 5,
     "d": 4,
     "l": 6,
     "f": 17,
     "a": 24,
     "gd": -7,
     "pts": 19
    },
    {
     "pos": 11,
     "team": "Ekwendeni United FC",
     "p": 17,
     "w": 4,
     "d": 6,
     "l": 7,
     "f": 22,
     "a": 23,
     "gd": -1,
     "pts": 18
    },
    {
     "pos": 12,
     "team": "Chizumulu United FC",
     "p": 15,
     "w": 5,
     "d": 3,
     "l": 7,
     "f": 25,
     "a": 31,
     "gd": -6,
     "pts": 18
    },
    {
     "pos": 13,
     "team": "Chipolopolo Boys FC",
     "p": 16,
     "w": 5,
     "d": 3,
     "l": 8,
     "f": 19,
     "a": 35,
     "gd": -16,
     "pts": 18
    },
    {
     "pos": 14,
     "team": "Chisapa FC",
     "p": 17,
     "w": 4,
     "d": 5,
     "l": 8,
     "f": 21,
     "a": 32,
     "gd": -11,
     "pts": 17
    },
    {
     "pos": 15,
     "team": "Euthin Kuseli Veterans FC",
     "p": 17,
     "w": 3,
     "d": 5,
     "l": 9,
     "f": 17,
     "a": 35,
     "gd": -18,
     "pts": 14
    },
    {
     "pos": 16,
     "team": "Chirambo FC",
     "p": 17,
     "w": 3,
     "d": 4,
     "l": 10,
     "f": 20,
     "a": 36,
     "gd": -16,
     "pts": 13
    }
   ],
   "notes": [
    "수정(무 칸): M'mbelwa 5→3, Chibavi 3→5, Ekwendeni Hardnockers 2→4, Ekwaiweni Tafika 4→2, Chihame 5→4"
   ]
  },
  {
   "key": 21,
   "short": "후반기 18주차",
   "label": "후반기 18주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 17,
     "w": 12,
     "d": 1,
     "l": 4,
     "f": 35,
     "a": 9,
     "gd": 26,
     "pts": 37
    },
    {
     "pos": 2,
     "team": "Raiply FC",
     "p": 17,
     "w": 10,
     "d": 4,
     "l": 3,
     "f": 38,
     "a": 18,
     "gd": 20,
     "pts": 34
    },
    {
     "pos": 3,
     "team": "Lube Masters FC",
     "p": 17,
     "w": 9,
     "d": 3,
     "l": 5,
     "f": 35,
     "a": 29,
     "gd": 6,
     "pts": 30
    },
    {
     "pos": 4,
     "team": "Sporting FC",
     "p": 17,
     "w": 8,
     "d": 5,
     "l": 4,
     "f": 34,
     "a": 18,
     "gd": 16,
     "pts": 29
    },
    {
     "pos": 5,
     "team": "Simbowe Stars FC",
     "p": 18,
     "w": 8,
     "d": 5,
     "l": 5,
     "f": 31,
     "a": 20,
     "gd": 11,
     "pts": 29
    },
    {
     "pos": 6,
     "team": "M'mbelwa Warriors FC",
     "p": 18,
     "w": 8,
     "d": 3,
     "l": 7,
     "f": 28,
     "a": 29,
     "gd": -1,
     "pts": 27
    },
    {
     "pos": 7,
     "team": "Chibavi Real Stars FC",
     "p": 16,
     "w": 7,
     "d": 5,
     "l": 4,
     "f": 37,
     "a": 24,
     "gd": 13,
     "pts": 26
    },
    {
     "pos": 8,
     "team": "Chihame All Stars",
     "p": 18,
     "w": 6,
     "d": 4,
     "l": 8,
     "f": 20,
     "a": 32,
     "gd": -12,
     "pts": 22
    },
    {
     "pos": 9,
     "team": "Ekwaiweni Tafika AS",
     "p": 16,
     "w": 6,
     "d": 2,
     "l": 8,
     "f": 22,
     "a": 26,
     "gd": -4,
     "pts": 20
    },
    {
     "pos": 10,
     "team": "Ekwendeni Hardnockers FC",
     "p": 15,
     "w": 5,
     "d": 4,
     "l": 6,
     "f": 17,
     "a": 24,
     "gd": -7,
     "pts": 19
    },
    {
     "pos": 11,
     "team": "Ekwendeni United FC",
     "p": 17,
     "w": 4,
     "d": 6,
     "l": 7,
     "f": 22,
     "a": 23,
     "gd": -1,
     "pts": 18
    },
    {
     "pos": 12,
     "team": "Chizumulu United FC",
     "p": 15,
     "w": 5,
     "d": 3,
     "l": 7,
     "f": 25,
     "a": 31,
     "gd": -6,
     "pts": 18
    },
    {
     "pos": 13,
     "team": "Chipolopolo Boys FC",
     "p": 16,
     "w": 5,
     "d": 3,
     "l": 8,
     "f": 19,
     "a": 35,
     "gd": -16,
     "pts": 18
    },
    {
     "pos": 14,
     "team": "Chisapa FC",
     "p": 17,
     "w": 4,
     "d": 5,
     "l": 8,
     "f": 21,
     "a": 32,
     "gd": -11,
     "pts": 17
    },
    {
     "pos": 15,
     "team": "Euthin Kuseli Veterans FC",
     "p": 17,
     "w": 3,
     "d": 5,
     "l": 9,
     "f": 17,
     "a": 35,
     "gd": -18,
     "pts": 14
    },
    {
     "pos": 16,
     "team": "Chirambo FC",
     "p": 17,
     "w": 3,
     "d": 4,
     "l": 10,
     "f": 20,
     "a": 36,
     "gd": -16,
     "pts": 13
    }
   ],
   "notes": []
  },
  {
   "key": 22,
   "short": "후반기 19주차",
   "label": "후반기 19주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 19,
     "w": 14,
     "d": 1,
     "l": 4,
     "f": 38,
     "a": 9,
     "gd": 29,
     "pts": 43
    },
    {
     "pos": 2,
     "team": "Simbowe Stars FC",
     "p": 21,
     "w": 11,
     "d": 5,
     "l": 5,
     "f": 37,
     "a": 20,
     "gd": 17,
     "pts": 38
    },
    {
     "pos": 3,
     "team": "Raiply FC",
     "p": 18,
     "w": 11,
     "d": 4,
     "l": 3,
     "f": 39,
     "a": 18,
     "gd": 21,
     "pts": 37
    },
    {
     "pos": 4,
     "team": "M'mbelwa Warriors FC",
     "p": 21,
     "w": 11,
     "d": 3,
     "l": 7,
     "f": 39,
     "a": 31,
     "gd": 8,
     "pts": 36
    },
    {
     "pos": 5,
     "team": "Lube Masters FC",
     "p": 17,
     "w": 9,
     "d": 3,
     "l": 5,
     "f": 35,
     "a": 29,
     "gd": 6,
     "pts": 30
    },
    {
     "pos": 6,
     "team": "Sporting FC",
     "p": 19,
     "w": 8,
     "d": 5,
     "l": 6,
     "f": 34,
     "a": 20,
     "gd": 14,
     "pts": 29
    },
    {
     "pos": 7,
     "team": "Chibavi Real Stars FC",
     "p": 17,
     "w": 7,
     "d": 5,
     "l": 5,
     "f": 37,
     "a": 26,
     "gd": 11,
     "pts": 26
    },
    {
     "pos": 8,
     "team": "Ekwaiweni Tafika AS",
     "p": 18,
     "w": 7,
     "d": 2,
     "l": 9,
     "f": 24,
     "a": 29,
     "gd": -5,
     "pts": 23
    },
    {
     "pos": 9,
     "team": "Chihame All Stars",
     "p": 20,
     "w": 6,
     "d": 4,
     "l": 10,
     "f": 21,
     "a": 35,
     "gd": -14,
     "pts": 22
    },
    {
     "pos": 10,
     "team": "Ekwendeni United FC",
     "p": 19,
     "w": 5,
     "d": 6,
     "l": 8,
     "f": 26,
     "a": 29,
     "gd": -3,
     "pts": 21
    },
    {
     "pos": 11,
     "team": "Chipolopolo Boys FC",
     "p": 18,
     "w": 6,
     "d": 3,
     "l": 9,
     "f": 22,
     "a": 37,
     "gd": -15,
     "pts": 21
    },
    {
     "pos": 12,
     "team": "Ekwendeni Hardnockers FC",
     "p": 15,
     "w": 5,
     "d": 4,
     "l": 6,
     "f": 17,
     "a": 24,
     "gd": -7,
     "pts": 19
    },
    {
     "pos": 13,
     "team": "Chizumulu United FC",
     "p": 16,
     "w": 5,
     "d": 3,
     "l": 8,
     "f": 26,
     "a": 35,
     "gd": -9,
     "pts": 18
    },
    {
     "pos": 14,
     "team": "Chisapa FC",
     "p": 18,
     "w": 4,
     "d": 5,
     "l": 9,
     "f": 21,
     "a": 35,
     "gd": -14,
     "pts": 17
    },
    {
     "pos": 15,
     "team": "Euthin Kuseli Veterans FC",
     "p": 19,
     "w": 4,
     "d": 5,
     "l": 10,
     "f": 19,
     "a": 37,
     "gd": -18,
     "pts": 17
    },
    {
     "pos": 16,
     "team": "Chirambo FC",
     "p": 19,
     "w": 3,
     "d": 4,
     "l": 12,
     "f": 20,
     "a": 41,
     "gd": -21,
     "pts": 13
    }
   ],
   "notes": [
    "사진 제목은 'WEEK 18'로 표기되어 있으나 18주차 표 다음 시점의 수치라 19주차로 추정",
    "수정: Euthin Kuseli 승 3→4"
   ]
  },
  {
   "key": 23,
   "short": "후반기 20주차",
   "label": "후반기 20주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 21,
     "w": 15,
     "d": 2,
     "l": 4,
     "f": 41,
     "a": 11,
     "gd": 30,
     "pts": 47
    },
    {
     "pos": 2,
     "team": "Simbowe Stars FC",
     "p": 22,
     "w": 12,
     "d": 5,
     "l": 5,
     "f": 39,
     "a": 21,
     "gd": 18,
     "pts": 41
    },
    {
     "pos": 3,
     "team": "Raiply FC",
     "p": 19,
     "w": 12,
     "d": 4,
     "l": 3,
     "f": 44,
     "a": 19,
     "gd": 25,
     "pts": 40
    },
    {
     "pos": 4,
     "team": "M'mbelwa Warriors FC",
     "p": 22,
     "w": 11,
     "d": 3,
     "l": 8,
     "f": 39,
     "a": 33,
     "gd": 6,
     "pts": 36
    },
    {
     "pos": 5,
     "team": "Lube Masters FC",
     "p": 19,
     "w": 10,
     "d": 3,
     "l": 6,
     "f": 37,
     "a": 32,
     "gd": 5,
     "pts": 33
    },
    {
     "pos": 6,
     "team": "Chibavi Real Stars FC",
     "p": 19,
     "w": 8,
     "d": 5,
     "l": 6,
     "f": 41,
     "a": 28,
     "gd": 13,
     "pts": 29
    },
    {
     "pos": 7,
     "team": "Sporting FC",
     "p": 20,
     "w": 8,
     "d": 5,
     "l": 7,
     "f": 34,
     "a": 23,
     "gd": 11,
     "pts": 29
    },
    {
     "pos": 8,
     "team": "Ekwaiweni Tafika AS",
     "p": 19,
     "w": 8,
     "d": 2,
     "l": 9,
     "f": 26,
     "a": 29,
     "gd": -3,
     "pts": 26
    },
    {
     "pos": 9,
     "team": "Chihame All Stars",
     "p": 21,
     "w": 7,
     "d": 4,
     "l": 10,
     "f": 23,
     "a": 35,
     "gd": -12,
     "pts": 25
    },
    {
     "pos": 10,
     "team": "Chipolopolo Boys FC",
     "p": 20,
     "w": 7,
     "d": 4,
     "l": 9,
     "f": 27,
     "a": 40,
     "gd": -13,
     "pts": 25
    },
    {
     "pos": 11,
     "team": "Ekwendeni United FC",
     "p": 20,
     "w": 5,
     "d": 6,
     "l": 9,
     "f": 28,
     "a": 33,
     "gd": -5,
     "pts": 21
    },
    {
     "pos": 12,
     "team": "Chizumulu United FC",
     "p": 17,
     "w": 6,
     "d": 3,
     "l": 8,
     "f": 27,
     "a": 35,
     "gd": -8,
     "pts": 21
    },
    {
     "pos": 13,
     "team": "Ekwendeni Hardnockers FC",
     "p": 16,
     "w": 5,
     "d": 4,
     "l": 7,
     "f": 18,
     "a": 26,
     "gd": -8,
     "pts": 19
    },
    {
     "pos": 14,
     "team": "Chisapa FC",
     "p": 20,
     "w": 4,
     "d": 5,
     "l": 11,
     "f": 21,
     "a": 38,
     "gd": -17,
     "pts": 17
    },
    {
     "pos": 15,
     "team": "Euthin Kuseli Veterans FC",
     "p": 20,
     "w": 4,
     "d": 5,
     "l": 11,
     "f": 20,
     "a": 42,
     "gd": -22,
     "pts": 17
    },
    {
     "pos": 16,
     "team": "Chirambo FC",
     "p": 21,
     "w": 4,
     "d": 4,
     "l": 13,
     "f": 23,
     "a": 43,
     "gd": -20,
     "pts": 16
    }
   ],
   "notes": []
  },
  {
   "key": 24,
   "short": "후반기 21주차",
   "label": "후반기 21주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 22,
     "w": 16,
     "d": 2,
     "l": 4,
     "f": 43,
     "a": 12,
     "gd": 31,
     "pts": 50
    },
    {
     "pos": 2,
     "team": "Raiply FC",
     "p": 20,
     "w": 12,
     "d": 5,
     "l": 3,
     "f": 46,
     "a": 21,
     "gd": 25,
     "pts": 41
    },
    {
     "pos": 3,
     "team": "Simbowe Stars FC",
     "p": 23,
     "w": 12,
     "d": 5,
     "l": 6,
     "f": 40,
     "a": 23,
     "gd": 17,
     "pts": 41
    },
    {
     "pos": 4,
     "team": "M'mbelwa Warriors FC",
     "p": 23,
     "w": 12,
     "d": 3,
     "l": 8,
     "f": 43,
     "a": 33,
     "gd": 10,
     "pts": 39
    },
    {
     "pos": 5,
     "team": "Lube Masters FC",
     "p": 20,
     "w": 11,
     "d": 3,
     "l": 6,
     "f": 39,
     "a": 33,
     "gd": 6,
     "pts": 36
    },
    {
     "pos": 6,
     "team": "Chibavi Real Stars FC",
     "p": 20,
     "w": 9,
     "d": 5,
     "l": 6,
     "f": 43,
     "a": 29,
     "gd": 14,
     "pts": 32
    },
    {
     "pos": 7,
     "team": "Sporting FC",
     "p": 21,
     "w": 8,
     "d": 6,
     "l": 7,
     "f": 36,
     "a": 25,
     "gd": 11,
     "pts": 30
    },
    {
     "pos": 8,
     "team": "Ekwaiweni Tafika AS",
     "p": 20,
     "w": 8,
     "d": 2,
     "l": 10,
     "f": 26,
     "a": 33,
     "gd": -7,
     "pts": 26
    },
    {
     "pos": 9,
     "team": "Chihame All Stars",
     "p": 22,
     "w": 7,
     "d": 4,
     "l": 11,
     "f": 24,
     "a": 37,
     "gd": -13,
     "pts": 25
    },
    {
     "pos": 10,
     "team": "Chipolopolo Boys FC",
     "p": 21,
     "w": 7,
     "d": 4,
     "l": 10,
     "f": 28,
     "a": 42,
     "gd": -14,
     "pts": 25
    },
    {
     "pos": 11,
     "team": "Chizumulu United FC",
     "p": 18,
     "w": 7,
     "d": 3,
     "l": 8,
     "f": 29,
     "a": 35,
     "gd": -6,
     "pts": 24
    },
    {
     "pos": 12,
     "team": "Ekwendeni Hardnockers FC",
     "p": 17,
     "w": 6,
     "d": 4,
     "l": 7,
     "f": 20,
     "a": 26,
     "gd": -6,
     "pts": 22
    },
    {
     "pos": 13,
     "team": "Ekwendeni United FC",
     "p": 21,
     "w": 5,
     "d": 6,
     "l": 10,
     "f": 28,
     "a": 35,
     "gd": -7,
     "pts": 21
    },
    {
     "pos": 14,
     "team": "Euthin Kuseli Veterans FC",
     "p": 21,
     "w": 5,
     "d": 5,
     "l": 11,
     "f": 22,
     "a": 42,
     "gd": -20,
     "pts": 20
    },
    {
     "pos": 15,
     "team": "Chisapa FC",
     "p": 21,
     "w": 4,
     "d": 5,
     "l": 12,
     "f": 21,
     "a": 40,
     "gd": -19,
     "pts": 17
    },
    {
     "pos": 16,
     "team": "Chirambo FC",
     "p": 22,
     "w": 4,
     "d": 4,
     "l": 14,
     "f": 23,
     "a": 45,
     "gd": -22,
     "pts": 16
    }
   ],
   "notes": [
    "수정: Embangweni 승 17→16, Ekwaiweni Tafika 득실차 -2→-7, Chirambo 경기수 21→22"
   ]
  },
  {
   "key": 25,
   "short": "후반기 22주차",
   "label": "후반기 22주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 23,
     "w": 17,
     "d": 2,
     "l": 4,
     "f": 47,
     "a": 13,
     "gd": 34,
     "pts": 53
    },
    {
     "pos": 2,
     "team": "Raiply FC",
     "p": 21,
     "w": 12,
     "d": 5,
     "l": 4,
     "f": 46,
     "a": 23,
     "gd": 23,
     "pts": 41
    },
    {
     "pos": 3,
     "team": "Simbowe Stars FC",
     "p": 24,
     "w": 12,
     "d": 5,
     "l": 7,
     "f": 40,
     "a": 24,
     "gd": 16,
     "pts": 41
    },
    {
     "pos": 4,
     "team": "M'mbelwa Warriors FC",
     "p": 24,
     "w": 12,
     "d": 3,
     "l": 9,
     "f": 43,
     "a": 34,
     "gd": 9,
     "pts": 39
    },
    {
     "pos": 5,
     "team": "Lube Masters FC",
     "p": 21,
     "w": 12,
     "d": 3,
     "l": 6,
     "f": 40,
     "a": 33,
     "gd": 7,
     "pts": 39
    },
    {
     "pos": 6,
     "team": "Chibavi Real Stars FC",
     "p": 21,
     "w": 10,
     "d": 5,
     "l": 6,
     "f": 44,
     "a": 29,
     "gd": 15,
     "pts": 35
    },
    {
     "pos": 7,
     "team": "Sporting FC",
     "p": 21,
     "w": 8,
     "d": 6,
     "l": 7,
     "f": 36,
     "a": 25,
     "gd": 11,
     "pts": 30
    },
    {
     "pos": 8,
     "team": "Ekwaiweni Tafika AS",
     "p": 21,
     "w": 9,
     "d": 2,
     "l": 10,
     "f": 27,
     "a": 33,
     "gd": -6,
     "pts": 29
    },
    {
     "pos": 9,
     "team": "Chihame All Stars",
     "p": 23,
     "w": 8,
     "d": 4,
     "l": 11,
     "f": 26,
     "a": 38,
     "gd": -12,
     "pts": 28
    },
    {
     "pos": 10,
     "team": "Chipolopolo Boys FC",
     "p": 22,
     "w": 7,
     "d": 4,
     "l": 11,
     "f": 28,
     "a": 43,
     "gd": -15,
     "pts": 25
    },
    {
     "pos": 11,
     "team": "Chizumulu United FC",
     "p": 19,
     "w": 7,
     "d": 3,
     "l": 9,
     "f": 30,
     "a": 37,
     "gd": -7,
     "pts": 24
    },
    {
     "pos": 12,
     "team": "Ekwendeni Hardnockers FC",
     "p": 17,
     "w": 6,
     "d": 4,
     "l": 7,
     "f": 20,
     "a": 26,
     "gd": -6,
     "pts": 22
    },
    {
     "pos": 13,
     "team": "Ekwendeni United FC",
     "p": 21,
     "w": 5,
     "d": 6,
     "l": 10,
     "f": 28,
     "a": 35,
     "gd": -7,
     "pts": 21
    },
    {
     "pos": 14,
     "team": "Euthin Kuseli Veterans FC",
     "p": 21,
     "w": 5,
     "d": 5,
     "l": 11,
     "f": 22,
     "a": 42,
     "gd": -20,
     "pts": 20
    },
    {
     "pos": 15,
     "team": "Chirambo FC",
     "p": 23,
     "w": 5,
     "d": 4,
     "l": 14,
     "f": 25,
     "a": 45,
     "gd": -20,
     "pts": 19
    },
    {
     "pos": 16,
     "team": "Chisapa FC",
     "p": 22,
     "w": 4,
     "d": 5,
     "l": 13,
     "f": 22,
     "a": 44,
     "gd": -22,
     "pts": 17
    }
   ],
   "notes": []
  },
  {
   "key": 26,
   "short": "후반기 23주차",
   "label": "후반기 23주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 24,
     "w": 18,
     "d": 2,
     "l": 4,
     "f": 49,
     "a": 13,
     "gd": 36,
     "pts": 56
    },
    {
     "pos": 2,
     "team": "Lube Masters FC",
     "p": 23,
     "w": 13,
     "d": 4,
     "l": 6,
     "f": 44,
     "a": 36,
     "gd": 8,
     "pts": 43
    },
    {
     "pos": 3,
     "team": "Raiply FC",
     "p": 22,
     "w": 12,
     "d": 5,
     "l": 5,
     "f": 47,
     "a": 25,
     "gd": 22,
     "pts": 41
    },
    {
     "pos": 4,
     "team": "Simbowe Stars FC",
     "p": 24,
     "w": 12,
     "d": 5,
     "l": 7,
     "f": 40,
     "a": 24,
     "gd": 16,
     "pts": 41
    },
    {
     "pos": 5,
     "team": "M'mbelwa Warriors FC",
     "p": 24,
     "w": 12,
     "d": 3,
     "l": 9,
     "f": 43,
     "a": 34,
     "gd": 9,
     "pts": 39
    },
    {
     "pos": 6,
     "team": "Chibavi Real Stars FC",
     "p": 22,
     "w": 11,
     "d": 5,
     "l": 6,
     "f": 46,
     "a": 29,
     "gd": 17,
     "pts": 38
    },
    {
     "pos": 7,
     "team": "Sporting FC",
     "p": 23,
     "w": 8,
     "d": 7,
     "l": 8,
     "f": 38,
     "a": 29,
     "gd": 9,
     "pts": 31
    },
    {
     "pos": 8,
     "team": "Ekwaiweni Tafika AS",
     "p": 22,
     "w": 9,
     "d": 2,
     "l": 11,
     "f": 27,
     "a": 34,
     "gd": -7,
     "pts": 29
    },
    {
     "pos": 9,
     "team": "Chipolopolo Boys FC",
     "p": 23,
     "w": 8,
     "d": 4,
     "l": 11,
     "f": 30,
     "a": 43,
     "gd": -13,
     "pts": 28
    },
    {
     "pos": 10,
     "team": "Chihame All Stars",
     "p": 24,
     "w": 8,
     "d": 4,
     "l": 12,
     "f": 26,
     "a": 40,
     "gd": -14,
     "pts": 28
    },
    {
     "pos": 11,
     "team": "Chizumulu United FC",
     "p": 20,
     "w": 8,
     "d": 3,
     "l": 9,
     "f": 32,
     "a": 37,
     "gd": -5,
     "pts": 27
    },
    {
     "pos": 12,
     "team": "Ekwendeni Hardnockers FC",
     "p": 20,
     "w": 6,
     "d": 5,
     "l": 9,
     "f": 21,
     "a": 31,
     "gd": -10,
     "pts": 23
    },
    {
     "pos": 13,
     "team": "Euthin Kuseli Veterans FC",
     "p": 23,
     "w": 6,
     "d": 5,
     "l": 12,
     "f": 25,
     "a": 45,
     "gd": -20,
     "pts": 23
    },
    {
     "pos": 14,
     "team": "Ekwendeni United FC",
     "p": 22,
     "w": 5,
     "d": 7,
     "l": 10,
     "f": 28,
     "a": 35,
     "gd": -7,
     "pts": 22
    },
    {
     "pos": 15,
     "team": "Chirambo FC",
     "p": 24,
     "w": 6,
     "d": 4,
     "l": 14,
     "f": 26,
     "a": 45,
     "gd": -19,
     "pts": 22
    },
    {
     "pos": 16,
     "team": "Chisapa FC",
     "p": 22,
     "w": 4,
     "d": 5,
     "l": 13,
     "f": 22,
     "a": 44,
     "gd": -22,
     "pts": 17
    }
   ],
   "notes": []
  },
  {
   "key": 27,
   "short": "후반기 24주차",
   "label": "후반기 24주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 25,
     "w": 19,
     "d": 2,
     "l": 4,
     "f": 51,
     "a": 13,
     "gd": 38,
     "pts": 59
    },
    {
     "pos": 2,
     "team": "Lube Masters FC",
     "p": 25,
     "w": 14,
     "d": 4,
     "l": 7,
     "f": 46,
     "a": 38,
     "gd": 8,
     "pts": 46
    },
    {
     "pos": 3,
     "team": "Simbowe Stars FC",
     "p": 26,
     "w": 13,
     "d": 6,
     "l": 7,
     "f": 44,
     "a": 25,
     "gd": 19,
     "pts": 45
    },
    {
     "pos": 4,
     "team": "Raiply FC",
     "p": 23,
     "w": 12,
     "d": 5,
     "l": 6,
     "f": 47,
     "a": 26,
     "gd": 21,
     "pts": 41
    },
    {
     "pos": 5,
     "team": "Chibavi Real Stars FC",
     "p": 24,
     "w": 11,
     "d": 6,
     "l": 7,
     "f": 48,
     "a": 33,
     "gd": 15,
     "pts": 39
    },
    {
     "pos": 6,
     "team": "M'mbelwa Warriors FC",
     "p": 25,
     "w": 12,
     "d": 3,
     "l": 10,
     "f": 43,
     "a": 36,
     "gd": 7,
     "pts": 39
    },
    {
     "pos": 7,
     "team": "Chipolopolo Boys FC",
     "p": 25,
     "w": 9,
     "d": 5,
     "l": 11,
     "f": 31,
     "a": 43,
     "gd": -12,
     "pts": 32
    },
    {
     "pos": 8,
     "team": "Sporting FC",
     "p": 23,
     "w": 8,
     "d": 7,
     "l": 8,
     "f": 38,
     "a": 29,
     "gd": 9,
     "pts": 31
    },
    {
     "pos": 9,
     "team": "Chihame All Stars",
     "p": 25,
     "w": 9,
     "d": 4,
     "l": 12,
     "f": 28,
     "a": 41,
     "gd": -13,
     "pts": 31
    },
    {
     "pos": 10,
     "team": "Ekwaiweni Tafika AS",
     "p": 23,
     "w": 9,
     "d": 2,
     "l": 12,
     "f": 28,
     "a": 36,
     "gd": -8,
     "pts": 29
    },
    {
     "pos": 11,
     "team": "Chizumulu United FC",
     "p": 20,
     "w": 8,
     "d": 3,
     "l": 9,
     "f": 32,
     "a": 37,
     "gd": -5,
     "pts": 27
    },
    {
     "pos": 12,
     "team": "Ekwendeni Hardnockers FC",
     "p": 22,
     "w": 7,
     "d": 5,
     "l": 10,
     "f": 22,
     "a": 32,
     "gd": -10,
     "pts": 26
    },
    {
     "pos": 13,
     "team": "Chirambo FC",
     "p": 25,
     "w": 7,
     "d": 4,
     "l": 14,
     "f": 27,
     "a": 45,
     "gd": -18,
     "pts": 25
    },
    {
     "pos": 14,
     "team": "Euthin Kuseli Veterans FC",
     "p": 25,
     "w": 6,
     "d": 6,
     "l": 13,
     "f": 27,
     "a": 48,
     "gd": -21,
     "pts": 24
    },
    {
     "pos": 15,
     "team": "Ekwendeni United FC",
     "p": 23,
     "w": 5,
     "d": 7,
     "l": 11,
     "f": 29,
     "a": 39,
     "gd": -10,
     "pts": 22
    },
    {
     "pos": 16,
     "team": "Chisapa FC",
     "p": 23,
     "w": 5,
     "d": 5,
     "l": 13,
     "f": 25,
     "a": 45,
     "gd": -20,
     "pts": 20
    }
   ],
   "notes": []
  },
  {
   "key": 28,
   "short": "후반기 25주차",
   "label": "후반기 25주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 26,
     "w": 19,
     "d": 2,
     "l": 5,
     "f": 52,
     "a": 15,
     "gd": 37,
     "pts": 59
    },
    {
     "pos": 2,
     "team": "Lube Masters FC",
     "p": 25,
     "w": 14,
     "d": 4,
     "l": 7,
     "f": 46,
     "a": 38,
     "gd": 8,
     "pts": 46
    },
    {
     "pos": 3,
     "team": "Simbowe Stars FC",
     "p": 26,
     "w": 13,
     "d": 6,
     "l": 7,
     "f": 44,
     "a": 25,
     "gd": 19,
     "pts": 45
    },
    {
     "pos": 4,
     "team": "Chibavi Real Stars FC",
     "p": 25,
     "w": 12,
     "d": 6,
     "l": 7,
     "f": 50,
     "a": 33,
     "gd": 17,
     "pts": 42
    },
    {
     "pos": 5,
     "team": "Raiply FC",
     "p": 24,
     "w": 12,
     "d": 5,
     "l": 7,
     "f": 47,
     "a": 28,
     "gd": 19,
     "pts": 41
    },
    {
     "pos": 6,
     "team": "M'mbelwa Warriors FC",
     "p": 26,
     "w": 12,
     "d": 3,
     "l": 11,
     "f": 44,
     "a": 38,
     "gd": 6,
     "pts": 39
    },
    {
     "pos": 7,
     "team": "Sporting FC",
     "p": 24,
     "w": 9,
     "d": 7,
     "l": 8,
     "f": 42,
     "a": 32,
     "gd": 10,
     "pts": 34
    },
    {
     "pos": 8,
     "team": "Chihame All Stars",
     "p": 26,
     "w": 10,
     "d": 4,
     "l": 12,
     "f": 30,
     "a": 42,
     "gd": -12,
     "pts": 34
    },
    {
     "pos": 9,
     "team": "Ekwaiweni Tafika AS",
     "p": 24,
     "w": 10,
     "d": 2,
     "l": 12,
     "f": 30,
     "a": 36,
     "gd": -6,
     "pts": 32
    },
    {
     "pos": 10,
     "team": "Chipolopolo Boys FC",
     "p": 26,
     "w": 9,
     "d": 5,
     "l": 12,
     "f": 33,
     "a": 46,
     "gd": -13,
     "pts": 32
    },
    {
     "pos": 11,
     "team": "Ekwendeni Hardnockers FC",
     "p": 24,
     "w": 8,
     "d": 5,
     "l": 11,
     "f": 24,
     "a": 34,
     "gd": -10,
     "pts": 29
    },
    {
     "pos": 12,
     "team": "Chirambo FC",
     "p": 26,
     "w": 8,
     "d": 4,
     "l": 14,
     "f": 29,
     "a": 46,
     "gd": -17,
     "pts": 28
    },
    {
     "pos": 13,
     "team": "Chizumulu United FC",
     "p": 21,
     "w": 8,
     "d": 3,
     "l": 10,
     "f": 32,
     "a": 39,
     "gd": -7,
     "pts": 27
    },
    {
     "pos": 14,
     "team": "Euthin Kuseli Veterans FC",
     "p": 26,
     "w": 7,
     "d": 6,
     "l": 13,
     "f": 30,
     "a": 50,
     "gd": -20,
     "pts": 27
    },
    {
     "pos": 15,
     "team": "Ekwendeni United FC",
     "p": 23,
     "w": 5,
     "d": 7,
     "l": 11,
     "f": 29,
     "a": 39,
     "gd": -10,
     "pts": 22
    },
    {
     "pos": 16,
     "team": "Chisapa FC",
     "p": 24,
     "w": 5,
     "d": 5,
     "l": 14,
     "f": 28,
     "a": 49,
     "gd": -21,
     "pts": 20
    }
   ],
   "notes": []
  },
  {
   "key": 29,
   "short": "후반기 26주차",
   "label": "후반기 26주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 27,
     "w": 19,
     "d": 2,
     "l": 6,
     "f": 52,
     "a": 16,
     "gd": 36,
     "pts": 59
    },
    {
     "pos": 2,
     "team": "Lube Masters FC",
     "p": 26,
     "w": 15,
     "d": 4,
     "l": 7,
     "f": 48,
     "a": 38,
     "gd": 10,
     "pts": 49
    },
    {
     "pos": 3,
     "team": "Simbowe Stars FC",
     "p": 27,
     "w": 14,
     "d": 6,
     "l": 7,
     "f": 47,
     "a": 26,
     "gd": 21,
     "pts": 48
    },
    {
     "pos": 4,
     "team": "Chibavi Real Stars FC",
     "p": 25,
     "w": 12,
     "d": 6,
     "l": 7,
     "f": 50,
     "a": 33,
     "gd": 17,
     "pts": 42
    },
    {
     "pos": 5,
     "team": "Raiply FC",
     "p": 25,
     "w": 12,
     "d": 5,
     "l": 8,
     "f": 48,
     "a": 31,
     "gd": 17,
     "pts": 41
    },
    {
     "pos": 6,
     "team": "Sporting FC",
     "p": 26,
     "w": 11,
     "d": 7,
     "l": 8,
     "f": 52,
     "a": 33,
     "gd": 19,
     "pts": 40
    },
    {
     "pos": 7,
     "team": "M'mbelwa Warriors FC",
     "p": 26,
     "w": 12,
     "d": 3,
     "l": 11,
     "f": 44,
     "a": 38,
     "gd": 6,
     "pts": 39
    },
    {
     "pos": 8,
     "team": "Chihame All Stars",
     "p": 26,
     "w": 10,
     "d": 4,
     "l": 12,
     "f": 30,
     "a": 42,
     "gd": -12,
     "pts": 34
    },
    {
     "pos": 9,
     "team": "Ekwaiweni Tafika AS",
     "p": 24,
     "w": 10,
     "d": 2,
     "l": 12,
     "f": 30,
     "a": 36,
     "gd": -6,
     "pts": 32
    },
    {
     "pos": 10,
     "team": "Chipolopolo Boys FC",
     "p": 26,
     "w": 9,
     "d": 5,
     "l": 12,
     "f": 33,
     "a": 46,
     "gd": -13,
     "pts": 32
    },
    {
     "pos": 11,
     "team": "Chizumulu United FC",
     "p": 22,
     "w": 9,
     "d": 3,
     "l": 10,
     "f": 37,
     "a": 40,
     "gd": -3,
     "pts": 30
    },
    {
     "pos": 12,
     "team": "Euthin Kuseli Veterans FC",
     "p": 28,
     "w": 8,
     "d": 6,
     "l": 14,
     "f": 31,
     "a": 54,
     "gd": -23,
     "pts": 30
    },
    {
     "pos": 13,
     "team": "Ekwendeni Hardnockers FC",
     "p": 25,
     "w": 8,
     "d": 5,
     "l": 12,
     "f": 25,
     "a": 40,
     "gd": -15,
     "pts": 29
    },
    {
     "pos": 14,
     "team": "Chirambo FC",
     "p": 26,
     "w": 8,
     "d": 4,
     "l": 14,
     "f": 29,
     "a": 46,
     "gd": -17,
     "pts": 28
    },
    {
     "pos": 15,
     "team": "Ekwendeni United FC",
     "p": 24,
     "w": 5,
     "d": 7,
     "l": 12,
     "f": 30,
     "a": 44,
     "gd": -14,
     "pts": 22
    },
    {
     "pos": 16,
     "team": "Chisapa FC",
     "p": 25,
     "w": 5,
     "d": 5,
     "l": 15,
     "f": 28,
     "a": 51,
     "gd": -23,
     "pts": 20
    }
   ],
   "notes": []
  },
  {
   "key": 30,
   "short": "후반기 27주차",
   "label": "후반기 27주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 27,
     "w": 19,
     "d": 2,
     "l": 6,
     "f": 52,
     "a": 16,
     "gd": 36,
     "pts": 59
    },
    {
     "pos": 2,
     "team": "Lube Masters FC",
     "p": 26,
     "w": 15,
     "d": 4,
     "l": 7,
     "f": 48,
     "a": 38,
     "gd": 10,
     "pts": 49
    },
    {
     "pos": 3,
     "team": "Simbowe Stars FC",
     "p": 27,
     "w": 14,
     "d": 6,
     "l": 7,
     "f": 47,
     "a": 26,
     "gd": 21,
     "pts": 48
    },
    {
     "pos": 4,
     "team": "Chibavi Real Stars FC",
     "p": 26,
     "w": 13,
     "d": 6,
     "l": 7,
     "f": 53,
     "a": 33,
     "gd": 20,
     "pts": 45
    },
    {
     "pos": 5,
     "team": "M'mbelwa Warriors FC",
     "p": 28,
     "w": 13,
     "d": 3,
     "l": 12,
     "f": 46,
     "a": 40,
     "gd": 6,
     "pts": 42
    },
    {
     "pos": 6,
     "team": "Raiply FC",
     "p": 25,
     "w": 12,
     "d": 5,
     "l": 8,
     "f": 48,
     "a": 31,
     "gd": 17,
     "pts": 41
    },
    {
     "pos": 7,
     "team": "Sporting FC",
     "p": 27,
     "w": 11,
     "d": 7,
     "l": 9,
     "f": 53,
     "a": 35,
     "gd": 18,
     "pts": 40
    },
    {
     "pos": 8,
     "team": "Chihame All Stars",
     "p": 27,
     "w": 10,
     "d": 5,
     "l": 12,
     "f": 31,
     "a": 43,
     "gd": -12,
     "pts": 35
    },
    {
     "pos": 9,
     "team": "Ekwaiweni Tafika AS",
     "p": 25,
     "w": 10,
     "d": 2,
     "l": 13,
     "f": 30,
     "a": 39,
     "gd": -9,
     "pts": 32
    },
    {
     "pos": 10,
     "team": "Chipolopolo Boys FC",
     "p": 26,
     "w": 9,
     "d": 5,
     "l": 12,
     "f": 33,
     "a": 46,
     "gd": -13,
     "pts": 32
    },
    {
     "pos": 11,
     "team": "Ekwendeni Hardnockers FC",
     "p": 26,
     "w": 9,
     "d": 5,
     "l": 12,
     "f": 26,
     "a": 40,
     "gd": -14,
     "pts": 32
    },
    {
     "pos": 12,
     "team": "Chizumulu United FC",
     "p": 22,
     "w": 9,
     "d": 3,
     "l": 10,
     "f": 37,
     "a": 40,
     "gd": -3,
     "pts": 30
    },
    {
     "pos": 13,
     "team": "Euthin Kuseli Veterans FC",
     "p": 28,
     "w": 8,
     "d": 6,
     "l": 14,
     "f": 31,
     "a": 54,
     "gd": -23,
     "pts": 30
    },
    {
     "pos": 14,
     "team": "Chirambo FC",
     "p": 26,
     "w": 8,
     "d": 4,
     "l": 14,
     "f": 29,
     "a": 46,
     "gd": -17,
     "pts": 28
    },
    {
     "pos": 15,
     "team": "Ekwendeni United FC",
     "p": 24,
     "w": 5,
     "d": 7,
     "l": 12,
     "f": 30,
     "a": 44,
     "gd": -14,
     "pts": 22
    },
    {
     "pos": 16,
     "team": "Chisapa FC",
     "p": 26,
     "w": 5,
     "d": 6,
     "l": 15,
     "f": 29,
     "a": 52,
     "gd": -23,
     "pts": 21
    }
   ],
   "notes": []
  },
  {
   "key": 31,
   "short": "후반기 28주차",
   "label": "후반기 28주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 29,
     "w": 20,
     "d": 2,
     "l": 7,
     "f": 58,
     "a": 18,
     "gd": 40,
     "pts": 62
    },
    {
     "pos": 2,
     "team": "Simbowe Stars FC",
     "p": 29,
     "w": 15,
     "d": 7,
     "l": 7,
     "f": 52,
     "a": 29,
     "gd": 23,
     "pts": 52
    },
    {
     "pos": 3,
     "team": "Lube Masters FC",
     "p": 27,
     "w": 16,
     "d": 4,
     "l": 7,
     "f": 51,
     "a": 40,
     "gd": 11,
     "pts": 52
    },
    {
     "pos": 4,
     "team": "Chibavi Real Stars FC",
     "p": 28,
     "w": 15,
     "d": 6,
     "l": 7,
     "f": 57,
     "a": 35,
     "gd": 22,
     "pts": 51
    },
    {
     "pos": 5,
     "team": "Raiply FC",
     "p": 27,
     "w": 13,
     "d": 5,
     "l": 9,
     "f": 50,
     "a": 33,
     "gd": 17,
     "pts": 44
    },
    {
     "pos": 6,
     "team": "M'mbelwa Warriors FC",
     "p": 29,
     "w": 13,
     "d": 3,
     "l": 13,
     "f": 46,
     "a": 43,
     "gd": 3,
     "pts": 42
    },
    {
     "pos": 7,
     "team": "Sporting FC",
     "p": 28,
     "w": 11,
     "d": 7,
     "l": 10,
     "f": 54,
     "a": 37,
     "gd": 17,
     "pts": 40
    },
    {
     "pos": 8,
     "team": "Chihame All Stars",
     "p": 28,
     "w": 10,
     "d": 6,
     "l": 12,
     "f": 33,
     "a": 45,
     "gd": -12,
     "pts": 36
    },
    {
     "pos": 9,
     "team": "Chipolopolo Boys FC",
     "p": 29,
     "w": 10,
     "d": 5,
     "l": 14,
     "f": 35,
     "a": 52,
     "gd": -17,
     "pts": 35
    },
    {
     "pos": 10,
     "team": "Chizumulu United FC",
     "p": 25,
     "w": 10,
     "d": 3,
     "l": 12,
     "f": 41,
     "a": 50,
     "gd": -9,
     "pts": 33
    },
    {
     "pos": 11,
     "team": "Ekwendeni Hardnockers FC",
     "p": 28,
     "w": 9,
     "d": 6,
     "l": 13,
     "f": 28,
     "a": 43,
     "gd": -15,
     "pts": 33
    },
    {
     "pos": 12,
     "team": "Euthin Kuseli Veterans FC",
     "p": 29,
     "w": 9,
     "d": 6,
     "l": 14,
     "f": 34,
     "a": 54,
     "gd": -20,
     "pts": 33
    },
    {
     "pos": 13,
     "team": "Ekwaiweni Tafika AS",
     "p": 25,
     "w": 10,
     "d": 2,
     "l": 13,
     "f": 30,
     "a": 39,
     "gd": -9,
     "pts": 32
    },
    {
     "pos": 14,
     "team": "Chirambo FC",
     "p": 28,
     "w": 8,
     "d": 5,
     "l": 15,
     "f": 32,
     "a": 50,
     "gd": -18,
     "pts": 29
    },
    {
     "pos": 15,
     "team": "Ekwendeni United FC",
     "p": 26,
     "w": 6,
     "d": 7,
     "l": 13,
     "f": 33,
     "a": 47,
     "gd": -14,
     "pts": 25
    },
    {
     "pos": 16,
     "team": "Chisapa FC",
     "p": 27,
     "w": 6,
     "d": 6,
     "l": 15,
     "f": 33,
     "a": 52,
     "gd": -19,
     "pts": 24
    }
   ],
   "notes": [
    "확인 필요: Chipolopolo Boys·Chisapa 행은 27주차/29·30주차와 누적이 맞지 않음 (Chisapa 승 6, Chipolopolo 득실 등) - 원본 사진 재확인 필요"
   ]
  },
  {
   "key": 32,
   "short": "후반기 29주차",
   "label": "후반기 29주차",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 29,
     "w": 20,
     "d": 2,
     "l": 7,
     "f": 58,
     "a": 18,
     "gd": 40,
     "pts": 62
    },
    {
     "pos": 2,
     "team": "Simbowe Stars FC",
     "p": 30,
     "w": 16,
     "d": 7,
     "l": 7,
     "f": 55,
     "a": 31,
     "gd": 24,
     "pts": 55
    },
    {
     "pos": 3,
     "team": "Lube Masters FC",
     "p": 28,
     "w": 17,
     "d": 4,
     "l": 7,
     "f": 53,
     "a": 40,
     "gd": 13,
     "pts": 55
    },
    {
     "pos": 4,
     "team": "Chibavi Real Stars FC",
     "p": 29,
     "w": 16,
     "d": 6,
     "l": 7,
     "f": 60,
     "a": 35,
     "gd": 25,
     "pts": 54
    },
    {
     "pos": 5,
     "team": "Raiply FC",
     "p": 29,
     "w": 15,
     "d": 5,
     "l": 9,
     "f": 55,
     "a": 35,
     "gd": 20,
     "pts": 50
    },
    {
     "pos": 6,
     "team": "M'mbelwa Warriors FC",
     "p": 30,
     "w": 14,
     "d": 3,
     "l": 13,
     "f": 48,
     "a": 43,
     "gd": 5,
     "pts": 45
    },
    {
     "pos": 7,
     "team": "Sporting FC",
     "p": 29,
     "w": 11,
     "d": 7,
     "l": 11,
     "f": 54,
     "a": 39,
     "gd": 15,
     "pts": 40
    },
    {
     "pos": 8,
     "team": "Chizumulu United FC",
     "p": 27,
     "w": 12,
     "d": 3,
     "l": 12,
     "f": 45,
     "a": 50,
     "gd": -5,
     "pts": 39
    },
    {
     "pos": 9,
     "team": "Chipolopolo Boys FC",
     "p": 29,
     "w": 11,
     "d": 5,
     "l": 13,
     "f": 39,
     "a": 48,
     "gd": -9,
     "pts": 38
    },
    {
     "pos": 10,
     "team": "Chihame All Stars",
     "p": 28,
     "w": 10,
     "d": 6,
     "l": 12,
     "f": 33,
     "a": 45,
     "gd": -12,
     "pts": 36
    },
    {
     "pos": 11,
     "team": "Euthin Kuseli Veterans FC",
     "p": 30,
     "w": 10,
     "d": 6,
     "l": 14,
     "f": 36,
     "a": 54,
     "gd": -18,
     "pts": 36
    },
    {
     "pos": 12,
     "team": "Ekwendeni Hardnockers FC",
     "p": 29,
     "w": 9,
     "d": 6,
     "l": 14,
     "f": 28,
     "a": 46,
     "gd": -18,
     "pts": 33
    },
    {
     "pos": 13,
     "team": "Ekwaiweni Tafika AS",
     "p": 27,
     "w": 10,
     "d": 2,
     "l": 15,
     "f": 32,
     "a": 44,
     "gd": -12,
     "pts": 32
    },
    {
     "pos": 14,
     "team": "Chirambo FC",
     "p": 29,
     "w": 8,
     "d": 5,
     "l": 16,
     "f": 32,
     "a": 52,
     "gd": -20,
     "pts": 29
    },
    {
     "pos": 15,
     "team": "Ekwendeni United FC",
     "p": 28,
     "w": 6,
     "d": 7,
     "l": 15,
     "f": 35,
     "a": 52,
     "gd": -17,
     "pts": 25
    },
    {
     "pos": 16,
     "team": "Chisapa FC",
     "p": 29,
     "w": 5,
     "d": 6,
     "l": 18,
     "f": 29,
     "a": 60,
     "gd": -31,
     "pts": 21
    }
   ],
   "notes": []
  },
  {
   "key": 33,
   "short": "30주차 (최종)",
   "label": "후반기 30주차 - 시즌 종료 (Week 30, End of the Season, 2025-2026)",
   "rows": [
    {
     "pos": 1,
     "team": "Embangweni United FC",
     "p": 30,
     "w": 20,
     "d": 3,
     "l": 7,
     "f": 59,
     "a": 19,
     "gd": 40,
     "pts": 63
    },
    {
     "pos": 2,
     "team": "Lube Masters FC",
     "p": 30,
     "w": 18,
     "d": 4,
     "l": 8,
     "f": 56,
     "a": 44,
     "gd": 12,
     "pts": 58
    },
    {
     "pos": 3,
     "team": "Chibavi Real Stars FC",
     "p": 30,
     "w": 17,
     "d": 6,
     "l": 7,
     "f": 62,
     "a": 35,
     "gd": 27,
     "pts": 57
    },
    {
     "pos": 4,
     "team": "Simbowe Stars FC",
     "p": 30,
     "w": 16,
     "d": 7,
     "l": 7,
     "f": 55,
     "a": 31,
     "gd": 24,
     "pts": 55
    },
    {
     "pos": 5,
     "team": "Raiply FC",
     "p": 30,
     "w": 15,
     "d": 6,
     "l": 9,
     "f": 56,
     "a": 36,
     "gd": 20,
     "pts": 51
    },
    {
     "pos": 6,
     "team": "Chizumulu United FC",
     "p": 30,
     "w": 15,
     "d": 3,
     "l": 12,
     "f": 53,
     "a": 51,
     "gd": 2,
     "pts": 48
    },
    {
     "pos": 7,
     "team": "M'mbelwa Warriors FC",
     "p": 30,
     "w": 14,
     "d": 3,
     "l": 13,
     "f": 48,
     "a": 43,
     "gd": 5,
     "pts": 45
    },
    {
     "pos": 8,
     "team": "Sporting FC",
     "p": 30,
     "w": 11,
     "d": 7,
     "l": 12,
     "f": 54,
     "a": 41,
     "gd": 13,
     "pts": 40
    },
    {
     "pos": 9,
     "team": "Chipolopolo Boys FC",
     "p": 30,
     "w": 11,
     "d": 5,
     "l": 14,
     "f": 39,
     "a": 50,
     "gd": -11,
     "pts": 38
    },
    {
     "pos": 10,
     "team": "Ekwaiweni Tafika AS",
     "p": 30,
     "w": 11,
     "d": 4,
     "l": 15,
     "f": 36,
     "a": 46,
     "gd": -10,
     "pts": 37
    },
    {
     "pos": 11,
     "team": "Chihame All Stars",
     "p": 30,
     "w": 10,
     "d": 7,
     "l": 13,
     "f": 34,
     "a": 48,
     "gd": -14,
     "pts": 37
    },
    {
     "pos": 12,
     "team": "Euthin Kuseli Veterans FC",
     "p": 30,
     "w": 10,
     "d": 6,
     "l": 14,
     "f": 36,
     "a": 54,
     "gd": -18,
     "pts": 36
    },
    {
     "pos": 13,
     "team": "Ekwendeni Hardnockers FC",
     "p": 30,
     "w": 9,
     "d": 6,
     "l": 15,
     "f": 28,
     "a": 48,
     "gd": -20,
     "pts": 33
    },
    {
     "pos": 14,
     "team": "Ekwendeni United FC",
     "p": 30,
     "w": 7,
     "d": 8,
     "l": 15,
     "f": 38,
     "a": 53,
     "gd": -15,
     "pts": 29
    },
    {
     "pos": 15,
     "team": "Chirambo FC",
     "p": 30,
     "w": 8,
     "d": 5,
     "l": 17,
     "f": 32,
     "a": 54,
     "gd": -22,
     "pts": 29
    },
    {
     "pos": 16,
     "team": "Chisapa FC",
     "p": 30,
     "w": 5,
     "d": 6,
     "l": 19,
     "f": 29,
     "a": 62,
     "gd": -33,
     "pts": 21
    }
   ],
   "notes": [
    "1위 Embangweni United FC 우승(C), 14~16위 Ekwendeni United FC / Chirambo FC / Chisapa FC 강등(R)"
   ]
  }
 ]
};

// 작년 팀 이름 -> 올해 leagueData 의 nameEn. 확인된 팀만 적습니다.
// (이름이 같은 팀은 여기에 없어도 nameEn 으로 바로 찾습니다.)
const ARCHIVE_ALIAS_MAP = {
  "Simbowe Stars FC": "Mafu Stars FC",       // 개명 (확인됨)
  "Ekwendeni United FC": "Ekwendeni FC",     // 개명 (확인됨)
  "Chihame All Stars": "Chihame All Stars FC", // 표기 차이 ("FC"만 없음)
  "Euthin Kuseli Veterans FC": "Euthini Veterans FC" // 표기 차이 (확인됨)
};

// 작년 팀 이름 -> 한글 표기. 올해 leagueData 에 같은 이름이 있으면 그 nameKo 를 우선 쓰고,
// 여기에는 개명된 팀·올해 리그에 없는 팀의 "당시 이름" 한글 표기만 적습니다.
const ARCHIVE_NAME_KO = {
  "Simbowe Stars FC": "심보웨 스타즈 FC",                 // 현재 마푸 스타즈 FC (개명)
  "Ekwendeni United FC": "에크웬데니 유나이티드 FC",       // 현재 에크웬데니 FC (개명)
  "Euthin Kuseli Veterans FC": "에우티니 쿠셀리 베테랑스 FC", // 현재 에우티니 베테랑스 FC (표기 차이)
  "Chihame All Stars": "치하메 올스타즈",                  // 현재 치하메 올스타즈 FC (표기 차이)
  "Embangweni United FC": "엠방웨니 유나이티드 FC",
  "Ekwendeni Hardnockers FC": "에크웬데니 하드녹커스 FC",
  "Ekwaiweni Tafika AS": "에크와이웨니 타피카 AS",
  "Sporting FC": "스포르팅 FC",
  "Chirambo FC": "치람보 FC",
  "Chisapa FC": "치사파 FC"
};
